### ISSUE TITLE
How to run a saved model?

### ISSUE THREAD

**Issue by wahlforss** [huggingface/pytorch-pretrained-BERT#115]
How can you run the model without training the model? If we already trained a model with run_classifer?

**Comment by ymcui** [comment]
Just set `--do_train=False` in your python command would be fine.

**Comment by davidefiocco** [comment]
@wahlforss it looks like @thomwolf is planning to illustrate this in the examples soon.
You find some useful code to do what you suggest in https://github.com/huggingface/pytorch-pretrained-BERT/pull/112/

**Comment by thomwolf** [comment]
Hi this is now included in the new release 0.4.0 and there are examples on how you can save and reload the models in the updated run_classifier, run_squad and run_swag.
