### ISSUE TITLE
_load_from_state_dict() takes 7 positional arguments but 8 were given

### ISSUE THREAD

**Issue by guanlongtianzi** [huggingface/pytorch-pretrained-BERT#122]

**Comment by SummmerSnow** [comment]
This is caused by pytorch version.
I found , In 0.4.0 version, _load_from_state_dict() only take 7 arguments, but In 0.4.1 and this code, we need feed 8 arguments.

```
module._load_from_state_dict(
                state_dict, prefix, local_metadata, True, missing_keys, unexpected_keys, error_msgs)
```

local_metadata should be removed in pytorch 0.4.0

**Comment by thomwolf** [comment]
Ok thanks @SummmerSnow !
