### ISSUE TITLE
It's possible to avoid download the pretrained model?

### ISSUE THREAD

**Issue by rxy1212** [huggingface/pytorch-pretrained-BERT#136]
When I  run this code `model = BertModel.from_pretrained('bert-base-uncased')` , it would download a big file and sometimes that's very slow. Now I have download the model from [https://github.com/google-research/bert](url). So, It's possible to avoid download the pretrained model when I use pytorch-pretrained-BERT at the first time?

**Comment by rxy1212** [comment]
I just find the way.

**Comment by makkunda** [comment]
@rxy1212  could you explain the method used

**Comment by rxy1212** [comment]
@makkunda 
In `modeling.py`, you can find this codes
```
PRETRAINED_MODEL_ARCHIVE_MAP = {
    'bert-base-uncased': "https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased.tar.gz",
    'bert-large-uncased': "https://s3.amazonaws.com/models.huggingface.co/bert/bert-large-uncased.tar.gz",
    'bert-base-cased': "https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-cased.tar.gz",
    'bert-large-cased': "https://s3.amazonaws.com/models.huggingface.co/bert/bert-large-cased.tar.gz",
    'bert-base-multilingual-uncased': "https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-multilingual-uncased.tar.gz",
    'bert-base-multilingual-cased': "https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-multilingual-cased.tar.gz",
    'bert-base-chinese': "https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-chinese.tar.gz",
}
```

just download the model you need by the url and unzip it, then you will get `bert_config.json` and `pytorch_model.bin`. You can put them in a folder X.
Now, you can use `model = BertModel.from_pretrained('THE-PATH-OF-X')`
