### ISSUE TITLE
run_squad.py without GPU.. Without CUPY

### ISSUE THREAD

**Issue by sandtemp01** [huggingface/pytorch-pretrained-BERT#137]
I am trying to run_squad.py for QnA (Squad) case. Its dependency is on GPU.. i.e., cupy is to be installed.
In one of my environment I dont have GPU therefore cupy is not getting installed and I am not able to proceed with training.

Can I train on CPU itself?
following is I am trying to run:

```
python run_squad.py \
  --bert_model bert-base-uncased \
  --do_train \
  --do_predict \
  --do_lower_case \
  --train_file $SQUAD_DIR/train-v1.1.json \
  --predict_file $SQUAD_DIR/dev-v1.1.json \
  --train_batch_size 12 \
  --learning_rate 3e-5 \
  --num_train_epochs 2.0 \
  --max_seq_length 384 \
  --doc_stride 128 \
  --output_dir /tmp/debug_squad/
```
and I get following error:

```
RuntimeError: CUDA environment is not correctly set up
(see https://github.com/chainer/chainer#installation).No module named 'cupy'
```

**Comment by peterflat** [comment]
@SandeepBhutani What was the conclusion of this issue?

**Comment by SandeepBhutani** [comment]
Is this issue still open.. It can be closed.. It was an environment issue..
