### ISSUE TITLE
Embeddings from BERT for original tokens

### ISSUE THREAD

**Issue by iampuntre** [huggingface/pytorch-pretrained-BERT#148]
I am trying out the `extract_features.py` example program. I noticed that a sentence gets split into tokens and the embeddings are generated. For example, if you had the sentence “Definitely not”, and the corresponding workpieces can be [“Def”, “##in”, “##ite”, “##ly”, “not”].  It then generates the embeddings for these tokens.

My question is how do I train an NER system on CoNLL dataset? 

I want to extract embeddings for original tokens for training an NER with a neural architecture. If you have come across any resource that gives a clear explanation on how to carry this out, post it here.

**Comment by thomwolf** [comment]
Hi, you should read the discussion in #64. I left this issue open for reference on these questions.
Don't hesitate to participate there.
