### ISSUE TITLE
Speedup using NVIDIA Apex 

### ISSUE THREAD

**Issue by lliimsft** [huggingface/pytorch-pretrained-BERT#149]
Hi,

According to PR https://github.com/huggingface/pytorch-pretrained-BERT/pull/116, we should be able to achieve a 3-4 x speed up for both bert-base and bert-large. However, I can only achieve 2x speed up with  bert-base. My docker image uses CUDA9.0 while the discussion in the PR https://github.com/huggingface/pytorch-pretrained-BERT/pull/116 is based on CUDA10.0... I am wondering if that makes the difference....

Thanks

**Comment by thomwolf** [comment]
Maybe. You can try with pytorch docker image `dockerhub 1.0-cuda10.0-cudnn7` to debug, as we did in the discussion in PR #116.

**Comment by lliimsft** [comment]
Just verified that CUDA10.0 makes 4x speedup. It should be better to include this in the main document.

**Comment by Oxi84** [comment]
What GPU do you run ...
