### ISSUE TITLE
activation function in BERTIntermediate

### ISSUE THREAD

**Issue by lukovnikov** [huggingface/pytorch-pretrained-BERT#15]
BERTConfig is not used for `BERTIntermediate`'s activation function. `intermediate_act_fn` is always `gelu`. Is this normal?

https://github.com/huggingface/pytorch-pretrained-BERT/blob/master/modeling.py#L240

**Comment by thomwolf** [comment]
Yes, I hard coded that since the pre-trained models are all trained with gelu anyway.

**Comment by lukovnikov** [comment]
ok. but since config is there anyway, isn't it cleaner to use it (e.g. to avoid errors for people using configs that use a different activation for some reason) ?

**Comment by thomwolf** [comment]
Yes we can, I'll change that in the coming first release (unless you would like to submit a PR which I would be happy to merge).

**Comment by lukovnikov** [comment]
yeah let me clean up and I'll PR
