### ISSUE TITLE
Did you suport squad2.0

### ISSUE THREAD

**Issue by zhaoguangxiang** [huggingface/pytorch-pretrained-BERT#153]
What is the command to reproduce the results of squad2.0 reported in the  BERT.  
Thanks~

**Comment by elyase** [comment]
This is still not supported but should be soon. You can follow/try this PR by @abeljim here:

https://github.com/huggingface/pytorch-pretrained-BERT/pull/152

**Comment by thomwolf** [comment]
This is now on master
