### ISSUE TITLE
Weights of BertForQuestionAnswering not initialized from pretrained model

### ISSUE THREAD

**Issue by sandtemp01** [huggingface/pytorch-pretrained-BERT#160]
Trying to run cloned code from git but not able to train. Please suggest

`python run_squad.py   --bert_model bert-base-uncased   --do_train   --do_predict   --do_lower_case   --train_file $SQUAD_DIR/train-v1.1.json   --predict_file $SQUAD_DIR/dev-v1.1_sand.json   --train_batch_size 12   --learning_rate 3e-5   --num_train_epochs 2.0   --max_seq_length 384   --doc_stride 128   --output_dir debug_squad9`

I am constantly getting this error when run in training mode:

 ```
01/03/2019 12:22:39 - INFO - pytorch_pretrained_bert.modeling -   Weights of BertForQuestionAnswering not initialized from pretrained model: ['qa_outputs.weight', 'qa_outputs.bias']
01/03/2019 12:22:39 - INFO - pytorch_pretrained_bert.modeling -   Weights from pretrained model not used in BertForQuestionAnswering: ['cls.predictions.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.decoder.weight', 'cls.seq_relationship.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.LayerNorm.bias']
hon3.6/site-packages/torch/nn/functional.py", line 749, in dropout
    else _VF.dropout(input, p, training))
RuntimeError: $ Torch: not enough memory: you tried to allocate 0GB. Buy new RAM! at /pytorch/aten/src/TH/THGeneral.cpp:201
```

**Comment by thomwolf** [comment]
What kind of GPU are you using?

**Comment by sandtemp01** [comment]
I am on CPU as of now

**Comment by thomwolf** [comment]
I don't think it is possible to use BERT on CPU (didn't work for me). The model is too big.
If you find a way, feel free to re-open the issue.

**Comment by sandtemp01** [comment]
Thanks for confirmation. Is "Fine Tuning" training also not possible for "BERT BASE"  on CPU? 
Correct me if I am wrong, following command is doing fine tuning training only
`python run_squad.py --bert_model bert-base-uncased --do_train --do_predict --do_lower_case --train_file $SQUAD_DIR/train-v1.1.json --predict_file $SQUAD_DIR/dev-v1.1_sand.json --train_batch_size 12 --learning_rate 3e-5 --num_train_epochs 2.0 --max_seq_length 384 --doc_stride 128 --output_dir debug_squad9`

**Comment by thomwolf** [comment]
You are right.
And no, unfortunately, fine-tuning is not possible on CPU in my opinion.

**Comment by phdowling** [comment]
Sorry - why is the model "too big" to be trained on CPU? Shouldn't the memory requirements of the GPU and CPU be basically the same? As far as I can tell, BERT should run on 12GB GPUs, plenty of CPU machines have more RAM than that. Or is there a difference in how the model is materialized in memory between CPU and GPU training?

**Comment by thomwolf** [comment]
My first comment was badly worded. You can `run` the model on CPU but `training` it on CPU is unrealistic.

**Comment by phdowling** [comment]
Can you elaborate? My machine has 30gb of ram but indeed I've found I am running out of memory. How come a 12gb gpu is enough, what makes the difference? Also I'm talking about fine-tuning a multiple choice model, just for context.

**Comment by khaerulumam42** [comment]
How big your data @phdowling ? I have TPU for training, if you want I will give access to you

**Comment by magdacisowska** [comment]
Can someone elaborate on how to actually train the model? I though that by passing --train_file and --do_train we perform the actual training (fine-tuning).
