### ISSUE TITLE
got an unexpected keyword argument 'cache_dir'

### ISSUE THREAD

**Issue by chiyuzhang94** [huggingface/pytorch-pretrained-BERT#185]
I used the following code to run the job: `
export GLUE_DIR=./data

python3 run_classifier.py \
  --task_name COLA \
  --do_train \
  --do_eval \
  --do_lower_case \
  --data_dir $GLUE_DIR/ \
  --bert_model bert-large-uncased \
  --max_seq_length 20 \
  --train_batch_size 10 \
  --learning_rate 2e-5 \
  --num_train_epochs 2.0 \
  --output_dir ./output`

Then, I got the output:
`01/11/2019 02:02:55 - INFO - __main__ -   device: cpu n_gpu: 0, distributed training: False, 16-bits training: False
01/11/2019 02:02:56 - INFO - pytorch_pretrained_bert.tokenization -   loading vocabulary file https://s3.amazonaws.com/models.huggingface.co/bert/bert-large-uncased-vocab.txt from cache at /Users/chiyuzhang/.pytorch_pretrained_bert/9b3c03a36e83b13d5ba95ac965c9f9074a99e14340c523ab405703179e79fc46.542ce4285a40d23a559526243235df47c5f75c197f04f37d1a0c124c32c9a084
01/11/2019 02:02:56 - INFO - pytorch_pretrained_bert.modeling -   loading archive file https://s3.amazonaws.com/models.huggingface.co/bert/bert-large-uncased.tar.gz from cache at /Users/chiyuzhang/.pytorch_pretrained_bert/214d4777e8e3eb234563136cd3a49f6bc34131de836848454373fa43f10adc5e.abfbb80ee795a608acbf35c7bf2d2d58574df3887cdd94b355fc67e03fddba05
01/11/2019 02:02:56 - INFO - pytorch_pretrained_bert.modeling -   extracting archive file /Users/chiyuzhang/.pytorch_pretrained_bert/214d4777e8e3eb234563136cd3a49f6bc34131de836848454373fa43f10adc5e.abfbb80ee795a608acbf35c7bf2d2d58574df3887cdd94b355fc67e03fddba05 to temp dir /var/folders/j0/_kd2ppm53wnb6pjypwy3gc_00000gn/T/tmpynwe_15z
01/11/2019 02:03:06 - INFO - pytorch_pretrained_bert.modeling -   Model config {
  "attention_probs_dropout_prob": 0.1,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 1024,
  "initializer_range": 0.02,
  "intermediate_size": 4096,
  "max_position_embeddings": 512,
  "num_attention_heads": 16,
  "num_hidden_layers": 24,
  "type_vocab_size": 2,
  "vocab_size": 30522
}

Traceback (most recent call last):
  File "run_classifier.py", line 619, in <module>
    main()
  File "run_classifier.py", line 455, in main
    num_labels = 2)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pytorch_pretrained_bert/modeling.py", line 502, in from_pretrained
    model = cls(config, *inputs, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'cache_dir'`

Could you please help me to fix this problem?

**Comment by thomwolf** [comment]
You should update to the latest version of `pytorch_pretrained_bert`(`pip install pytorch_pretrained_bert --upgrade`)

**Comment by HiroshigeAoki** [comment]
Hi, I get the same issue, and I can’t solve it by upgrading of pytorch_pretrained_bert. What else to solve it?
