### ISSUE TITLE
run_classifier.py doesn't save any configurations and I can't load the trained model. 

### ISSUE THREAD

**Issue by anz2** [huggingface/pytorch-pretrained-BERT#194]

**Comment by anz2** [comment]
I trained BertForSequenceClassification model with cola dataset mode for binary classification. It saved only eval_results.txt and pytorch_model.bin files. When I am loading model again like:
model = BertForSequenceClassification.from_pretrained('models/') 
it produces such error:
with open(json_file, "r", encoding='utf-8') as reader:
FileNotFoundError: [Errno 2] No such file or directory: 'models/bert_config.json'

I trained models using the command:
export GLUE_DIR=data_dir_path; python run_classifier.py --task_name cola --do_train --do_eval --data_dir $GLUE_DIR/ --bert_model bert-base-multilingual-cased --max_seq_length 128 --train_batch_size 16 --learning_rate 2e-5 --num_train_epochs 3.0 --output_dir models/

Do I have any error with training script? 
How can I produce such config.json file to load model successfully?

**Comment by thomwolf** [comment]
You can fetch the configuration from S3 like it's [done in the example](https://github.com/huggingface/pytorch-pretrained-BERT/blob/master/examples/run_classifier.py#L560).

Alternatively, you can save the configuration with:
```python
with open('config.json', 'w') as f:
    f.write(model.config.to_json_string())
```
