### ISSUE TITLE
TODO statement on Question/Answering Model

### ISSUE THREAD

**Issue by phatlast96** [huggingface/pytorch-pretrained-BERT#196]
Has this been confirmed?
https://github.com/huggingface/pytorch-pretrained-BERT/blob/647c98353090ee411e1ef9016b2a458becfe36f9/pytorch_pretrained_bert/modeling.py#L1084

**Comment by thomwolf** [comment]
Not really, I've moved to something else since I don't expect this to change significantly the results.
I will remove the TODO.
