### ISSUE TITLE
How convert pytorch to tf checkpoint?

### ISSUE THREAD

**Issue by semsevens** [huggingface/pytorch-pretrained-BERT#211]
How convert pytorch to tf checkpoint?

**Comment by nikitakit** [comment]
I don't think such a conversion is currently implemented in this repository, but I have my own implementation here (if you're interested in adapting it for your use-case): https://github.com/nikitakit/self-attentive-parser/blob/8238e79e2089300db059eddff78229a09e254f70/export/export_bert.py#L94-L141

**Comment by thomwolf** [comment]
Thanks @nikitakit, do you think your scripts would make sense in the present repo as well or is it tided to your parsing application?

**Comment by thomwolf** [comment]
Closing this for now. Feel free to re-open.

**Comment by tholor** [comment]
Would be actually quite nice to have such a conversion script in order to serve pytorch models via [bert-as-service](https://github.com/hanxiao/bert-as-service)

**Comment by maxlund** [comment]
Any progress on this? As @tholor says, would be nice for bert-as-service. @nikitakit is it possible to run your script for any finetuned pytorch model? If so, any tips/suggestions on how to do that?

**Comment by thomwolf** [comment]
Re-opening the issue.
I don't have time to work on that at the moment but I would be happy to welcome a PR if there is interest in this feature.

**Comment by MarvinMogab** [comment]
Any news on this ?
