### ISSUE TITLE
Pytorch-Bert: Why this command: pip install pytorch-pretrained-bert doesn't work for me

### ISSUE THREAD

**Issue by abril4416** [huggingface/pytorch-pretrained-BERT#212]
I try to install pytorch-bert using the command: pip install pytorch-pretrained-bert
However this doesn't work for me.
And the feedback is below:

  Could not find a version that satisfies the requirement pytorch-pretrained-be
rt (from versions: )
No matching distribution found for pytorch-pretrained-bert

I also tried to update my pip, but in vain.
So how can I install bert? (Will the root of the issue be that I use python2.7?)

**Comment by davidefiocco** [comment]
Hi, most likely you'll have to switch to python 3.5 or newer!
https://pypi.org/project/pytorch-pretrained-bert/ (check for requirements in the page: `Requires: Python >=3.5.0`

**Comment by thomwolf** [comment]
Indeed

**Comment by Chao-Tang** [comment]
Need some help. I'm experiencing the same problem with Python 3.7.3

Error code:
ERROR: Could not find a version that satisfies the requirement torch>=0.4.1 (from pytorch-pretrained-bert==0.4.0) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch>=0.4.1 (from pytorch-pretrained-bert==0.4.0)

**Comment by thomwolf** [comment]
Try installing pytorch first following the official instruction on the pytorch website: https://pytorch.org/
