### ISSUE TITLE
how to add new vocabulary?

### ISSUE THREAD

**Issue by hahmyg** [huggingface/pytorch-pretrained-BERT#224]
for specific task, it is required to add new vocabulary for tokenizer.
It is ok that re-training for those vocabulary for me :)

Is it possible to add new vocabulary for tokenizer?

**Comment by thomwolf** [comment]
Hi @hahmyg, please refer to the relevant section in the original implementation repository: https://github.com/google-research/bert#learning-a-new-wordpiece-vocabulary.
