### ISSUE TITLE
max sentence length

### ISSUE THREAD

**Issue by RayXu14** [huggingface/pytorch-pretrained-BERT#225]
is there an max sentence length for this bert code?

**Comment by thomwolf** [comment]
Hi, 512 tokens if you use the pre-trained models. Any length you want if you train your models from scratch.

**Comment by tsungruihon** [comment]
could we set it smaller ? cause if i set it as 512, then result is out of memory

**Comment by thomwolf** [comment]
You can just send a smaller input in the model, no need to go to the max

**Comment by tsungruihon** [comment]
thank you @thomwolf
