### ISSUE TITLE
Training BERT behind a proxy server

### ISSUE THREAD

**Issue by PeliconA** [huggingface/pytorch-pretrained-BERT#235]
When I try to run BERT training, I get the following error during the vocabulary download:

requests.exceptions.ConnectionError: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /models.huggingface.co/bert/bert-large-uncased-vocab.txt (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fbb55377828>: Failed to establish a new connection: [Errno 110] Connection timed out'))

I am running the script behind a proxy server which I suspect is the cause of this error. Is there any way to remedy this?

**Comment by thomwolf** [comment]
You can download the Tensorflow weights from Google's BERT repo and convert them as detailed in the readme of the present repo.

**Comment by SaulML** [comment]
Hi tomwolf,

I am new to XLNet and have the same issue as above. 

Could you direct me to the readme of the issue? I am not able to find it.

I modified my code to resolve the issue to 

**model_file_address = '/myfolder/XLNetWork/xlnet-base-cased-config.json'**

But I get the below error on the line : 
**model = XLNetForSequenceClassification.from_pretrained(model_file_address,num_labels=len(tag2idx))**

Error:
**UnpicklingError: invalid load key, '{'.**

I am pretty much stucked.

Your help will be appreciated.

Thanks,

Saul

**Comment by iamxpy** [comment]
@SaulML Did you solve it? I got the same error, i.e. `UnpicklingError: invalid load key, '{'.`, when I tried to load pretrained bert using `model = BertForSequenceClassification.from_pretrained("/PathToBert/uncased_L-12_H-768_A-12/bert_config.json", num_labels=2)`, thanks in advance!

**Comment by thomwolf** [comment]
You can now supply a `proxies` argument to `from_pretrained` when you are using proxies.
Check the doc and docstrings.

**Comment by avidale** [comment]
Got the same error as @SaulML  and @iamxpy. Has anyone solved it?

**Comment by ShivanshuPurohit** [comment]
Got the same unpickling error. Was it solved?

**Comment by acd424** [comment]
I think you need to just have the path as the directory rather than the config file.
