### ISSUE TITLE
Tokenization doesn't seem to match BERT paper

### ISSUE THREAD

**Issue by JohnGiorgi** [huggingface/pytorch-pretrained-BERT#241]
In the [BERT paper](https://arxiv.org/abs/1810.04805) section 4.3 ("Named Entity Recognition") there is an example of some tokenized text:

```python
['Jim', 'Hen', '##son', 'was', 'a', 'puppet', '##eer']
```

However, when I take that sentence and try to tokenize it myself with `BertTokenizer` from this repo

```python
from pytorch_pretrained_bert import BertTokenizer

tokenizer = BertTokenizer.from_pretrained('bert-base-cased', do_lower_case=False)

text = "Jim Henson was a puppeteer"

tokenizer.tokenize(text) == ['Jim', 'He', '##nson', 'was', 'a', 'puppet', '##eer']
```

same thing happens if I pre-tokenize and just use `BertTokenizer.wordpiece_tokenizer.tokenize()`

```python
from itertools import chain
from pytorch_pretrained_bert import BertTokenizer

tokenizer = BertTokenizer.from_pretrained('bert-base-cased', do_lower_case=False)

text = "Jim Henson was a puppeteer".split()

list(chain.from_iterable([tokenizer.wordpiece_tokenizer.tokenize(token) for token in text])) == ['Jim', 'He', '##nson', 'was', 'a', 'puppet', '##eer']
```

Is there something I am misunderstanding / doing wrong or is this an actual bug? The BERT paper and this repo tokenize `"Henson"` as `['Hen', '##son']` and `['He', '##nson']` respectively.

**Comment by bheinzerling** [comment]
WordPiece tokenization depends on the particular BERT model: In general, one model, say, bert-based-cased will produce a different tokenization than another, say, bert-large-uncased.

If you try all models, one or more might produce the tokenization shown in the example in the paper.
It might also happen that none of them does, in which case the example was probably produced with an unpublished model.

A bug would be if the same model leads to different tokenizations in the pytorch and tensorflow version.

**Comment by JohnGiorgi** [comment]
Hmm, I see. I didn't know that, thanks for pointing it out!

For what it is worth, `bert-base-multilingual-cased` is the only model (from those currently listed in the readme of this repo) that produces the tokenization shown in the example in the paper.
