### ISSUE TITLE
can you do a new release + pypi

### ISSUE THREAD

**Issue by joelgrus** [huggingface/pytorch-pretrained-BERT#245]
we've been getting some requests to incorporate newer features into allennlp that are only on master (e.g. `never_split`).

thanks!

**Comment by thomwolf** [comment]
Hi Joel, yes the new release (0.5.0) is pretty much ready (remaining work on branches `fifth-release` and `transfo-xl` to finish testing the newly added pre-trained OpenAI GPT and Transformer-XL).

Likely next week.

**Comment by joelgrus** [comment]
Awesome, thanks!

**Comment by thomwolf** [comment]
Ok @joelgrus, the new release is out: https://github.com/huggingface/pytorch-pretrained-BERT/releases/tag/v0.5.0
