### ISSUE TITLE
Fine tuning Bert for Question answering 

### ISSUE THREAD

**Issue by MathewAlexander** [huggingface/pytorch-pretrained-BERT#249]
I just wanted to ask if the weights of the Bert base model are getting updated while fine tuning Bert for Question answering. I see that the  Bert for QA is a model with A linear layer on top of Bert pre-trained model. I am trying to reproduce the same model in keras. Could any one tell me if i should freeze the layers in the Bert base model or not?

**Comment by rodgzilla** [comment]
The weights of the BERT base model are getting updated while finetuning the network.

**Comment by thomwolf** [comment]
Indeed
