### ISSUE TITLE
potential bug in extract_features.py

### ISSUE THREAD

**Issue by jayleicn** [huggingface/pytorch-pretrained-BERT#263]
Hi,

`token_type_ids` is not set for this line: 
`all_encoder_layers, _ = model(input_ids, token_type_ids=None, attention_mask=input_mask)`
 https://github.com/huggingface/pytorch-pretrained-BERT/blob/master/examples/extract_features.py#L267, this does not affect single sequence feature extraction, but for a pair of sequence, the model will process the pair as a single sequence and add `A` embedding to the two sequences, which should add `A`, `B` respectively. Seems like a bug.

Best,
Jie

**Comment by thomwolf** [comment]
Hi Jie,
`extract_feature.py` is an example script. If you want to adapt it for sentences-pair, we would be happy to welcome a PR :)
