### ISSUE TITLE
RuntimeError: cuda runtime error while running run_classifier.py with 'bert-large-uncased' bert model

### ISSUE THREAD

**Issue by laibamehnaz** [huggingface/pytorch-pretrained-BERT#264]

**Comment by thomwolf** [comment]
reduce batch size?

**Comment by laibamehnaz** [comment]
It is 32 as of now . What do you think I should reduce it to ?

**Comment by thomwolf** [comment]
Start very low and increase while looking at `nvidia-smi` or a similar GPU memory visualization tool.

**Comment by thomwolf** [comment]
Closing this for now, feel free to re-open if you have other issues.
