### ISSUE TITLE
Missing files for Transformer-XL examples

### ISSUE THREAD

**Issue by stefan-it** [huggingface/pytorch-pretrained-BERT#267]
Hi,

thanks so much for the new *0.5.0* release. I wanted to train a `TransfoXLModel` model, as described in the `README` [here](https://github.com/huggingface/pytorch-pretrained-BERT/blame/master/README.md#L132).

Unfortunately, the files `transfo_xl_train.py` and `transfo_xl_eval.py` are not located in the `examples` directory.

Could you please add them to repository? Thanks :heart:

**Comment by thomwolf** [comment]
Oh yes, that was a typo, there is only one example for Transformer-XL and it's the `run_transfo_xl.py` file detailed [here](https://github.com/huggingface/pytorch-pretrained-BERT/blob/master/README.md#openai-gpt-and-transformer-xl-running-the-examples). Read the API details in the readme for more information on the input/outputs of the two Transformer-XL models.
I've updated the readme, thanks.
