### ISSUE TITLE
Too much info @ stdout

### ISSUE THREAD

**Issue by mahnerak** [huggingface/pytorch-pretrained-BERT#291]
As a library, it is preferred to have no unnecessary `print`s in the repo. Using the `pytorch-pretrained-BERT` makes it impossible to use `stdout` as main output mechanism for my code.
For example: it prints directly to `stdout` "Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex.".
I guess printing this kind of messages to `stderr` will be a better idea.

**Comment by thomwolf** [comment]
Oh that's right, this one should be a logging.info event like the other ones.

**Comment by thomwolf** [comment]
Fixed
