### ISSUE TITLE
bert.pooler.dense initialization 

### ISSUE THREAD

**Issue by SinghJasdeep** [huggingface/pytorch-pretrained-BERT#300]
Hey! Sorry if this is redundant. 

I saw 3 other issues asking similar questions but couldn't find these exact layers mentioned. 

Are bert.pooler.dense.weight  &  bert.pooler.dense.bias randomly initialized? 

Thank you so much!

**Comment by thomwolf** [comment]
Hi Jasdeep,
No, they are initialized from Google's pretrained model (they are trained for next sentence prediction task during pretraining).
