### ISSUE TITLE
`train_dataset` and `eval_dataset` in run_openai_gpt.py

### ISSUE THREAD

**Issue by bkj** [huggingface/pytorch-pretrained-BERT#301]
Running `examples/run_openai_gpt.py` w/ the default arguments throws an error:
```
$ python run_openai_gpt.py --output_dir tmp --do_eval
Traceback (most recent call last):
  File "run_openai_gpt.py", line 259, in <module>
    main()
  File "run_openai_gpt.py", line 153, in main
    train_dataset = load_rocstories_dataset(args.train_dataset)
  File "run_openai_gpt.py", line 49, in load_rocstories_dataset
    with open(dataset_path, encoding='utf_8') as f:
FileNotFoundError: [Errno 2] No such file or directory: ''
```

Looking at the code, it looks like `train_dataset` and `eval_dataset` need to be explicitly set.  Any suggestions on what they should be set to?

Thanks!

cc @thomwolf

**Comment by thomwolf** [comment]
Hi Ben,
Please read the [relevant example section in the readme](https://github.com/huggingface/pytorch-pretrained-BERT#fine-tuning-openai-gpt-on-the-rocstories-dataset).

**Comment by abs51295** [comment]
@thomwolf I see that the data is downloaded and cached in case of not providing the `train_dataset` and `eval_dataset` parameters: https://github.com/huggingface/pytorch-pretrained-BERT/blob/master/examples/run_openai_gpt.py#L152-L153, but it fails here: https://github.com/huggingface/pytorch-pretrained-BERT/blob/master/examples/run_openai_gpt.py#L162. So either we make the parameters required or do some additional steps which requires untar of the downloaded data and pointing towards that data. Let me know what you think.
