### ISSUE TITLE
Can I do a code reference in implementing my code?

### ISSUE THREAD

**Issue by graykode** [huggingface/pytorch-pretrained-BERT#304]
@thomwolf 
I am trying simply implementing gpt-2 on Pytorch
I have trouble in trasfering tensorflow checkpoint to pytorch :(
https://github.com/graykode/gpt-2-Pytorch
Could I do this code reference in implementing my code? I'll write reference in my code!!
Thanks for awesome sharing!

**Comment by thomwolf** [comment]
Hi @graykode,
What do you mean by "code reference"?

**Comment by graykode** [comment]
@thomwolf 
Hello thomwolf!
It's mean I show the origin of the information in my project code comment.
Thanks

**Comment by thomwolf** [comment]
Oh yes, no problem.
Just reference the origin of the work and the licences (inherited from the relevant authors and code I started from)

**Comment by graykode** [comment]
@thomwolf Sure, What license i follow? I already known original [openAi/gpt-2](https://github.com/openai/gpt-2) is MIT license, but pytorch-pretrained-BERT is Apache 2.0!
But I want to just use gpt-2 model and model transferring code!!
