### ISSUE TITLE
Tests error: Issue with python3 compatibility, on zope interface implementation

### ISSUE THREAD

**Issue by AprilSongRits** [huggingface/pytorch-pretrained-BERT#309]
Hi, I came across the following error after run **python -m pytest tests/modeling_test.py**

________________________________________________________________________________ ERROR collecting tests/modeling_test.py __________________________________________________________________________________
modeling_test.py:25: in <module>
    from pytorch_pretrained_bert import (BertConfig, BertModel, BertForMaskedLM,
/usr/local/lib/python3.6/site-packages/pytorch_pretrained_bert/__init__.py:7: in <module>
    from .modeling import (BertConfig, BertModel, BertForPreTraining,
/usr/local/lib/python3.6/site-packages/pytorch_pretrained_bert/modeling.py:218: in <module>
    from apex.normalization.fused_layer_norm import FusedLayerNorm as BertLayerNorm
/usr/local/lib/python3.6/site-packages/apex/__init__.py:18: in <module>
    from apex.interfaces import (ApexImplementation,
/usr/local/lib/python3.6/site-packages/apex/interfaces.py:10: in <module>
    class ApexImplementation(object):
/usr/local/lib/python3.6/site-packages/apex/interfaces.py:14: in ApexImplementation
    implements(IApex)
/usr/local/lib/python3.6/site-packages/zope/interface/declarations.py:483: in implements
    raise TypeError(_ADVICE_ERROR % 'implementer')
E   TypeError: Class advice impossible in Python3.  Use the @implementer class decorator instead.

**My configurations are as follows:
python version 3.6.4
CUDA Version 8.0.61
torch==1.0.1.post2
apex==0.9.10.dev0
zope.interface==4.6.0**

Thanks

**Comment by lemo2012** [comment]
any solution here?

**Comment by thomwolf** [comment]
This looks like an incompatibility between apex and zope.
Have you tried without installing apex?

**Comment by AprilSongRits** [comment]
> This looks like an incompatibility between apex and zope.
> Have you tried without installing apex?

I uninstalled apex, it works now!
Thank you so much!!!!
