### ISSUE TITLE
Shouldn't GPT2 use Linear instead of Conv1D?

### ISSUE THREAD

**Issue by spolu** [huggingface/pytorch-pretrained-BERT#311]
Conv1D seems to be inherited from GPT but does not seem to serve any special purpose in GPT2 (BERT uses Linear).

Should GPT2's model be moved to using Linear (which is easier to grasp obvioulsy)?

**Comment by spolu** [comment]
Maybe this would break pre-trained weights loading? Interested to understand if that's the only reason?

**Comment by thomwolf** [comment]
Possibility, feel free to test the modification and submit a PR @spolu!

**Comment by IdoAmit198** [comment]
Hi guys,
I also wondered whether anyone modified the gpt2 model to have nn.Linear instead of Conv1D layers (using the pre-trained weights).
Did any of you success or found such implementation?

**Comment by NamburiSrinath** [comment]
Hi folks,

I am working on a use case which takes only nn.Linear layers (so the code worked fine for BERT) but it didn't for GPT-2 because of the same reason?

Is there a way to change the Conv1D() to linear layers? Below is the actual gpt2 I was getting when using standard script form HF - 

```
GPT2Model(
  (wte): Embedding(50257, 768)
  (wpe): Embedding(1024, 768)
  (drop): Dropout(p=0.1, inplace=False)
  (h): ModuleList(
    (0-11): 12 x GPT2Block(
      (ln_1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
      (attn): GPT2Attention(
        (c_attn): Conv1D()
        (c_proj): Conv1D()
        (attn_dropout): Dropout(p=0.1, inplace=False)
        (resid_dropout): Dropout(p=0.1, inplace=False)
      )
      (ln_2): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
      (mlp): GPT2MLP(
        (c_fc): Conv1D()
        (c_proj): Conv1D()
        (act): NewGELUActivation()
        (dropout): Dropout(p=0.1, inplace=False)
      )
    )
  )
  (ln_f): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
)
```

**Comment by lakshith-403** [comment]
@NamburiSrinath @IdoAmit198

The difference between Convo1D and Linear layers is,
- In Linear layers weight matrix is transposed when doing the calculation
- In Convo1D no transpose occurs

So what you can do is,  Load the pre trained weights, get Convo1d layers transpose them and save it.

After this just replacing convo1D with linear layers will work fine.

**Comment by lakshith-403** [comment]
@NamburiSrinath @IdoAmit198

The difference between Convo1D and Linear layers is,
- In Linear layers weight matrix is transposed when doing the calculation
- In Convo1D no transpose occurs

So what you can do is,  get the state dict from the pre trained weights, get Convo1d layer entries and transpose those tensors.

After this just replace convo1D with linear layers and load the state dict to this new model.
