### ISSUE TITLE
run_classifier with evaluation job only

### ISSUE THREAD

**Issue by PaulZhangIsing** [huggingface/pytorch-pretrained-BERT#326]
Thanks for giving such awesome project.
However, I have encountered some problem.
After training the model, I just want to do eval on another dataset with the trained model. Therefore I only open do_eval.
However, it gives me this error:

Traceback (most recent call last):
  File "run_classifier_torch.py", line 687, in <module>
    main()
  File "run_classifier_torch.py", line 677, in main
    'loss': tr_loss/nb_tr_steps}
UnboundLocalError: local variable 'tr_loss' referenced before assignment

It seems that the loss and tr_loss are only declared in train. If we neglect the training process, the error shall pop up. 

solution : using eval_loss instead

**Comment by wuyinzhenjun** [comment]
evalonly works last ver, need to mv some code out of train...

**Comment by PaulZhangIsing** [comment]
> evalonly works last ver, need to mv some code out of train...

yup I agree. I try to claim some variable to be global...

**Comment by thomwolf** [comment]
Seems fixed in master, right? Feel free to re-open the issue if it's not the case.
