### ISSUE TITLE
run_lm_finetuning - ZeroDivisionError

### ISSUE THREAD

**Issue by naga-dsalgo** [huggingface/pytorch-pretrained-BERT#329]
Trying to get run_lm_finetunning example on working on below GPU machine but finding getting zeroDivisonError.Any idea what could be causing this error?

![image](https://user-images.githubusercontent.com/47925301/53542425-6c966800-3aec-11e9-9681-87432bcd6aee.png)

python /home/ec2-user/SageMaker/bert_pytorch/pytorch-pretrained-BERT/examples/run_lm_finetuning.py   --bert_model bert-base-uncased   --do_train   --train_file /home/ec2-user/SageMaker/bert_pytorch/pytorch-pretrained-BERT/samples/sample_text.txt   --output_dir /home/ec2-user/SageMaker/bert_pytorch/pytorch-pretrained-BERT/models   --num_train_epochs 5.0   --learning_rate 3e-5   --train_batch_size 32   --max_seq_length 32

![image](https://user-images.githubusercontent.com/47925301/53542336-01e52c80-3aec-11e9-9966-beecb8755d01.png)

**Comment by thomwolf** [comment]
Seems like an error with `t_total`. `t_total` is the number of training optimization steps of the optimizer defined [here](num_train_optimization_steps) in the `run_lm_finetuning` example.
Can you make sure it's not zero?

**Comment by vebits** [comment]
Your `batch_size` of 32 is too big for such a small `train_file`, i.e. sample_text.txt. Try setting `batch_size` to 16 or send in a larger train file with more text.
