### ISSUE TITLE
Feature Request: GPT2 fine tuning

### ISSUE THREAD

**Issue by eukaryote31** [huggingface/pytorch-pretrained-BERT#335]

**Comment by thomwolf** [comment]
Yes, feel free to open a PR if you want.
It's just a regular PyTorch model so all the standard ways of training a PyTorch model work.

**Comment by bakszero** [comment]
Is is possible to fine-tune GPT2 on downstream tasks currently?

**Comment by shizhediao** [comment]
same questions
