### ISSUE TITLE
BertEmbedding not initialized with `padding_idx=0`

### ISSUE THREAD

**Issue by cdjhz** [huggingface/pytorch-pretrained-BERT#344]
https://github.com/huggingface/pytorch-pretrained-BERT/blob/2152bfeae82439600dc5b5deab057a3c4331c62d/pytorch_pretrained_bert/modeling.py#L696

The bert-embeddings are not initialized with `padding_idx=0`, which may potentially result in none zero embeddings for zeros paddings in some early version of pytorch.

**Comment by thomwolf** [comment]
Could be, do you want to submit a PR to update this?

**Comment by thomwolf** [comment]
Closed by #358, thanks @cdjhz!
