### ISSUE TITLE
Unable to train (fine-tuning) BERT with small training set

### ISSUE THREAD

**Issue by shuvadibp** [huggingface/pytorch-pretrained-BERT#349]
I am trying to train BERT with 1 context and 1 answer in the train.json, I am getting the below error.
_lr_this_step = args.learning_rate * warmup_linear(global_step/t_total, args.warmup_proportion)
ZeroDivisionError: division by zero_
After training with 1 context and 5 answers, the error is avoided, but I do not see any change in the answer obtained from BERT. Please help regarding this and let me know if anyone has tried this fine tuning training.

**Comment by thomwolf** [comment]
Probably an issue with `t_total` and the number of training optimization steps similarly to #329.
Could you check the number of total training step sent to the optimizer? Which example script are you using?
