### ISSUE TITLE
How to incrementally do fine tune train 

### ISSUE THREAD

**Issue by shuvadibp** [huggingface/pytorch-pretrained-BERT#352]
I am using Bert for Question Answering. After fine tuning with Squad data set, I want to further train new questions of my own domain.   
Please suggest how can I use newly generated pytorch_model.bin file and then increment it with my own training weights to get my own pytorch_suqad_plus_my_model.bin ?

**Comment by maxlund** [comment]
I think my answer here can help you:
https://github.com/huggingface/pytorch-pretrained-BERT/issues/332

**Comment by dhruvkp090** [comment]
Hey @shuvadibp, did you figure out a way of doing it? I would like to talk to you about the same..
