### ISSUE TITLE
Ranking predictions with BertForQuestionAnswering

### ISSUE THREAD

**Issue by gqoew** [huggingface/pytorch-pretrained-BERT#360]
I am using `BertForQuestionAnswering`

I am trying to make a prediction from the same question asked on different paragraphs. It outputs an `OrderedDict` of tuples with format `(paragraphID, answer)`. How can I rank those predictions to get the most probable answer across all paragraphs?

Thanks for great repo!

**Comment by beyondbeneath** [comment]
I am also interested in this, it looks like we would have to append the prediction probability to the `all_predictions` JSON output.
