### ISSUE TITLE
how does the run_squad.py deal with non-answerable questions 

### ISSUE THREAD

**Issue by elephantomkk** [huggingface/pytorch-pretrained-BERT#367]
Hi, 

I want to do a similar reading comprehension task with non-answerable questions but i didn't figure out how you deal with it from the codes. Did you add additional token on this?  Or only outputs the no-answer when the start logit = end logit = -1? Thanks!

**Comment by thomwolf** [comment]
@Liangtaiwan and @abeljim were the contributors of the `run_squad.py` example.
Maybe they can help.

**Comment by Liangtaiwan** [comment]
Hi @elephantomkk,

The non-answerable solving is using [CLS] token as the ground truth.
As a result, the start login = and end logit = -1.

You can find it out in this repo code or official Bert code.
Also, the method is mentioned in Jacob Devlin's slide.
https://nlp.stanford.edu/seminar/details/jdevlin.pdf?fbclid=IwAR2TBFCJOeZ9cGhxB-z5cJJ17vHN4W25oWsjI8NqJoTEmlYIYEKG7oh4tlY

**Comment by elephantomkk** [comment]
Thanks for the reply! I tested that and found the performance on the non-answerable is not so good compared with the answerables:(

**Comment by Arjunsankarlal** [comment]
@Liangtaiwan and @abeljim I am quite confused with logit idea. There are some cases where I get the 

> "1": [
        {
            "text": "hover your mouse pointer",
            "probability": 1.0,
            "start_logit": -12.987695693969727,
            "end_logit": -12.40383529663086
        }
    ],

In this place, what these values actually mean ? , is there any full form for logit. An explanation in the code as a comment would help a lot!
