### ISSUE TITLE
BertForQuestionAnswering: How to split  output between query hidden state and context hidden state

### ISSUE THREAD

**Issue by julietokwara** [huggingface/pytorch-pretrained-BERT#369]
I've made several attempts to, but all seem to fail. Do you have a good way to do this? Right now, passing what i thought to just be the context hidden state to the final output layer in run_squad.py drops my scores (F1) by 10 points.

**Comment by mhattingpete** [comment]
If you want only the context you can find the index from the segment vector by finding the last first 1 in the vector and splitting the query_context on that index. Then the context will be everything after the 1 index and everything before will be the question.
