### ISSUE TITLE
Empty nbest_predictions.json for run_squad.py

### ISSUE THREAD

**Issue by yangl57** [huggingface/pytorch-pretrained-BERT#377]
This is due to extra indentation on line 623 in run_squad.py 
It should be outside of the "if else" loop.

**Comment by thomwolf** [comment]
Good catch! Do you want to submit a PR? Otherwise, I'll fix it in the next release.

**Comment by suamin** [comment]
Hi @thomwolf 
The issue still persists, there were two extra indentations and you removed only one to move the line out of inner if-else but, one more indentation should be removed to bring [L620](https://github.com/huggingface/pytorch-pretrained-BERT/blob/master/examples/run_squad.py#L620) out of outer if-else. Doing this produces non-empty `nbest_predictions.json` file.
