### ISSUE TITLE
truncated normal initializer

### ISSUE THREAD

**Issue by ruotianluo** [huggingface/pytorch-pretrained-BERT#38]
I have a reasonable truncated normal approximation. (Actually that is what tf does).
https://discuss.pytorch.org/t/implementing-truncated-normal-initializer/4778/16?u=ruotianluo

**Comment by thomwolf** [comment]
Yeah we could try that. Not sure how important it is though. Did you try it?

**Comment by thomwolf** [comment]
Ok I think we will stick to the normal_initializer for now. Thanks for indicating this option!
