### ISSUE TITLE
run_squad.py cannot predict only

### ISSUE THREAD

**Issue by lixinsu** [huggingface/pytorch-pretrained-BERT#387]
Existing code cannot load fine-tuned model properly.
https://github.com/huggingface/pytorch-pretrained-BERT/blob/f3e5404880902a1bdfed2b1d47d10a6c672dc430/examples/run_squad.py#L1011-L1025

**Comment by lixinsu** [comment]
It is better to imitate original Bert repo to add separate argument `args.vocab_file`, and during prediction,  argument `bert_model` is the directory of the fine-tuned model.

**Comment by thomwolf** [comment]
Make sense indeed. Would you like to submit a PR on that?
