### ISSUE TITLE
'NoneType' object with constructor

### ISSUE THREAD

**Issue by leelaylay** [huggingface/pytorch-pretrained-BERT#390]
I run the code below and often get 'NoneType' object. (I usually run multiprocessing)
```python
model = BertModel.from_pretrained('bert-base-uncased')
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
```

**Comment by supersweak** [comment]
Me too.It is probably Network connection problem.

**Comment by thomwolf** [comment]
The network connection check has been relaxed in the now merged #500.
It will be included in the next PyPI release (probably next week).
In the meantime you can install from `master`.

**Comment by leelaylay** [comment]
@thomwolf  Thank you.

**Comment by thomwolf** [comment]
The new release is on pypi!
