### ISSUE TITLE
Is the GPT-2 pretrained model language agnostic?

### ISSUE THREAD

**Issue by AlyShmahell** [huggingface/pytorch-pretrained-BERT#399]
I'm trying to build a language model that trains on a Polish corpus. And I'm wondering if the GPT-2 pretrained model you present supports that, or if it's English only.

Thank You.

**Comment by thomwolf** [comment]
Hi Aly, GPT-2 is pretrained on an English only corpus.

**Comment by AlyShmahell** [comment]
Hi @thomwolf , thank you for the clarification.
