### ISSUE TITLE
slow training speed even 20 steps

### ISSUE THREAD

**Issue by KavyaGujjala** [huggingface/pytorch-pretrained-BERT#408]
Hi,
I am running run_lm_finetuning.py code on a 1 million sentences .
It's taking more than 20 hours even for each epoch. 

where as run_pretraining.py code from google-research/bert takes very less time.

What can be the reason?

How to resolve this?

**Comment by thomwolf** [comment]
We have new lm_fintetuning scripts thanks to @Rocketknight1 PR #392.
Maybe you can try these ones.
They are in [`./examples/lm_finetuning/`](./examples/lm_finetuning/)
