### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by weiyumou** [huggingface/pytorch-pretrained-BERT#41]
I think I spotted a typo in the README file under the Usage header. There is a piece of code that uses `BertTokenizer` and the typo is on this line:
`tokenized_text = "Who was Jim Henson ? Jim Henson was a puppeteer"`

I think `tokenized_text` should be replaced with `text`, since the next line is
`tokenized_text = tokenizer.tokenize(text)`

**Comment by thomwolf** [comment]
Yes
