### ISSUE TITLE
something wrong in example

### ISSUE THREAD

**Issue by Wangpeiyi9979** [huggingface/pytorch-pretrained-BERT#410]
![image](https://user-images.githubusercontent.com/42565075/54999939-5789f780-500c-11e9-958f-1c7b0b92a257.png)

the segmentation is wrong。。

**Comment by thomwolf** [comment]
Do you have the latest `pytorch-pretrained-bert` ?
```python
import pytorch_pretrained_bert
pytorch_pretrained_bert.__version__
```

**Comment by Wangpeiyi9979** [comment]
Thank you so much!!!!!!!
