### ISSUE TITLE
Possible error in "pytorch-pretrained-BERT/examples/run_gpt2.py" unconditional

### ISSUE THREAD

**Issue by brunokinder** [huggingface/pytorch-pretrained-BERT#412]
Hello,
First of all thanks for offering us those great NLP implementations.

I think there may be an error in the file pytorch-pretrained-BERT/examples/run_gpt2.py
![image](https://user-images.githubusercontent.com/1786870/55035530-94df8c80-4fee-11e9-90eb-bde5bcba7832.png)

The way it is implemented if we do unconditional=True nothing happens.

If you fix this line, don't forget to look at too
![image](https://user-images.githubusercontent.com/1786870/55035656-dd974580-4fee-11e9-85e4-b0aa050fa274.png)

Thank you.

**Comment by thomwolf** [comment]
This should be fixed by #462.
