### ISSUE TITLE
pytorch model to tensorflow checkpoint

### ISSUE THREAD

**Issue by KavyaGujjala** [huggingface/pytorch-pretrained-BERT#421]
How to convert a pytorch_model.bin to tensorflow checkpoint?

**Comment by thomwolf** [comment]
Hi, there is no script to do that currently. I don't plan to add this feature in the short term but I would be happy to welcome  a PR on that.

**Comment by tholor** [comment]
A PR for this would be great. It would allow a simple deployment via Han's bert-as-service
 https://github.com/hanxiao/bert-as-service/
