### ISSUE TITLE
Cannot find Synthetic self-training in this repository.

### ISSUE THREAD

**Issue by Dogy06** [huggingface/pytorch-pretrained-BERT#428]
The SQuAD leader board's (https://rajpurkar.github.io/SQuAD-explorer/) 3rd highest scored model uses 'synthetic self-training'.
There is a PDF explaining it: https://nlp.stanford.edu/seminar/details/jdevlin.pdf?fbclid=IwAR2TBFCJOeZ9cGhxB-z5cJJ17vHN4W25oWsjI8NqJoTEmlYIYEKG7oh4tlY but I have found no such model within this repository.
On the leader board website, it shows me a link to this repository.
Is the synthetic self-training in this repository? (If so, please show me the link to the code)
Is it private? Will it be released?
Thanks,
Dogy06

By the way: I checked both the Pytorch and Tensorflow version of the code., I posted the same issue here:https://github.com/google-research/bert/issues/532

**Comment by thomwolf** [comment]
Hi, indeed there is no Synthetic self-training in this repository, and the SQuAD leaderboard website actually refers to the Tensorflow repository so I'll close this issue.

**Comment by dogydev** [comment]
Will you be adding synthetic self training though?
