### ISSUE TITLE
how to do the pre training the model form scratch?

### ISSUE THREAD

**Issue by loveJasmine** [huggingface/pytorch-pretrained-BERT#433]
for example, use sample_text.txt

**Comment by jeonsworld** [comment]
`python3 examples/lm_finetuning/simple_lm_finetuning.py 
--train_corpus sample_text.txt 
--bert_model bert-base-uncased 
--do_lower_case 
--output_dir finetuned_lm/
`

**Comment by thomwolf** [comment]
Yes let's keep a single issue on this. Closing in favor of #385.
