### ISSUE TITLE
DistributedDataParallel Not Working

### ISSUE THREAD

**Issue by moinnadeem** [huggingface/pytorch-pretrained-BERT#439]
Hi, I've been stuck on this for days, so I decided to make an issue.

When I run DistributedDataParallel with the PyTorch launch module, I see that one machine will start training without waiting for the other one to start; this is different than if I run it without the launch module. WIthout the launch module, I am also letting one process have access to multiple GPUs, rather than just one.

I'm following your implementation of DistributedDataParallel in your Medium article: https://medium.com/huggingface/training-larger-batches-practical-tips-on-1-gpu-multi-gpu-distributed-setups-ec88c3e51255

**Comment by thomwolf** [comment]
Hi @moinnadeem,
What is the hardware you are using and what is the exact command you are using to run DistributedDataParallel with the PyTorch launch module?
