### ISSUE TITLE
How can i use bert for finding word embeddings

### ISSUE THREAD

**Issue by gkv91** [huggingface/pytorch-pretrained-BERT#440]
Hi all,
Can I use pre-trained BERT for finding fixed sized word embeddings, like 300D Glove or Word2vec word embeddings?.

**Comment by heslowen** [comment]
I extract features like examples in extarct_features.py. But went I used these features(the last encoded_layers) as word embeddings, I got a worse result than using 300D Glove. I also used these features to compute the cos similarity for each word in  sentences, I found that all values were around 0.6

**Comment by marianalucut7** [comment]
Hi. I really need someone's help regarding using the bert model to extract the word embeddings: This script: https://github.com/huggingface/pytorch-pretrained-BERT/blob/master/examples/extract_features.py doesn't exist anymore.

Any suggestions instead that replaced this script?
