### ISSUE TITLE
pretrain for chinese dataset

### ISSUE THREAD

**Issue by XiangZhu0718** [huggingface/pytorch-pretrained-BERT#448]
Hi , I want to pretrain my model for chinese dataset . can i use my own vocab.txt ? 
and what is the format for vocab.txt ? thanks a lot

**Comment by thomwolf** [comment]
Hi, you should probably turn to the TensorFlow version for pre-training.
This package is mostly intended to be used for fine-tuning pre-trained models.
Another option for BERT-like pre-training is to use Facebook's [XLM](https://github.com/facebookresearch/XLM)

**Comment by jiahuanluo** [comment]
Hi, @thomwolf 

I want to finetune on Chinese dataset, but I found that there are a lot of [UNK] terms in one sentence. 
It is a common news dataset.

Is it normal?
