### ISSUE TITLE
max_seq_length for squad

### ISSUE THREAD

**Issue by ZhaofengWu** [huggingface/pytorch-pretrained-BERT#456]
The example script for squad sets `--max_seq_length` at 384 as default. However it seems that many paragraphs in squad exceed this length. Then what if the answer to some question lies in the truncated part of the paragraph?

**Comment by thomwolf** [comment]
Then you're doomed for this answer. There are a possibility to do a sliding window approach but we didn't implemented it in the examples of pytorch-pretrained-bert.
Check this issue (and the linked TensorFlow issue) for a discussion on this: https://github.com/huggingface/pytorch-pretrained-BERT/issues/89

**Comment by ronakice** [comment]
Actually, I feel like it is already implemented in run_squad.py?
