### ISSUE TITLE
Pooler weights not being updated for Multiple Choice models? 

### ISSUE THREAD

**Issue by meetshah1995** [huggingface/pytorch-pretrained-BERT#461]
I'm trying use pretrained BERT to finetune on a multiple choice dataset.

The parameters from `pooler` are excluded from the optimizer params [here](https://github.com/huggingface/pytorch-pretrained-BERT/blob/master/pytorch_pretrained_bert/modeling.py#L1044-L1047), however, the MutlipleChoice model does indeed use `pooled_output` (which passes through the `pooler`) [here](https://github.com/huggingface/pytorch-pretrained-BERT/blob/master/examples/run_swag.py#L392).

I wasn't able to find a similar exclusion of `pooler` params from the optimizer in the official repo. I think I'm missing something here. Thanks for your patience.

**Comment by thomwolf** [comment]
Indeed this looks like a bug in the `run_swag.py` example.
What do you think @rodgzilla?
Isn't the exclusion of the pooler parameters from optimization ([line 392 of `run_swag.py`](https://github.com/huggingface/pytorch-pretrained-BERT/blob/master/examples/run_swag.py#L392)) a typo?

**Comment by meetshah1995** [comment]
@thomwolf -  This surely looks like a bug, should I just send a hotfix and close it?

**Comment by thomwolf** [comment]
Yes!

**Comment by meetshah1995** [comment]
Fixed in #675.
