### ISSUE TITLE
How to get vocab.txt and bert_config.json as output of fine tuning?

### ISSUE THREAD

**Issue by search4mahesh** [huggingface/pytorch-pretrained-BERT#464]
Hi,
I am fine tuning bert on custom data.
As output I am getting only pytorch_model.bin but how to get updated vocab.txt and bert_config.json .

Please suggest.

Thanks
Mahesh

**Comment by thomwolf** [comment]
You can get `pytorch_model.bin` and `config.json` just as indicated in the examples: https://github.com/huggingface/pytorch-pretrained-BERT/blob/master/examples/run_classifier.py#L861-L866

The vocabulary stays the same, just load the tokenizer as you did for the training (`BertTokenizer.from_pretrained(...)`)

**Comment by search4mahesh** [comment]
Thanks Thomas. I really appreciate it.
Our custom text might have some new words which may not be in original vocab.txt
Original vocab.txt contain some unused placeholders. (some 993) out of total 30522
Please let me know your thoughts on this.
Thanks
Mahesh

**Comment by thomwolf** [comment]
Then you should go have a look at https://github.com/huggingface/pytorch-pretrained-BERT/issues/463.
And I will close this issue in favor of #463 ;-)
