### ISSUE TITLE
Why can`t we just use cached pytorch-model without internet

### ISSUE THREAD

**Issue by floAlpha** [huggingface/pytorch-pretrained-BERT#469]
Sorry for my Impolite words. I am very appreciate huggingface team for the excellent repo and 
my original intention is to provide some  suggestion to great repo to help more people like me, forgive me for being rude.

**Comment by Jonbean** [comment]
First, yes you can. You should be able to download the model(whether use shell command or python downloader) into a specified directory and modify the loading lines. That works for me. 
Second, please be appreciated to these fantastic works huggingface team pulled off. It's not their fault that you don't have stable access, so help yourself.

**Comment by thomwolf** [comment]
Humm wording apart, maybe we could relax the internet connection check indeed, I'll have a look.

**Comment by floAlpha** [comment]
Sincerely thank you for your reply, you are the great contributors, I apologize again for my inappropriate expression, mainly because I can`t properly solve the problem till midnight.  I just want to make my own suggestion for people encountered this like me, so I opened this issue. Actually I am very grateful for your work, and appreciate the open source community. Best regards!

**Comment by thomwolf** [comment]
Ok, network connection check has been relaxed in the now merged #500.
It will be included in the next PyPI release (probably next week).
In the meantime you can install from `master`.

**Comment by floAlpha** [comment]
So nice you are，I cannot continue my research without pytorch-pretrained-BERT，Thank you for your Incredible devotion.With my sincere apology.

**Comment by Swarzkopf314** [comment]
I'd like to ask why model.from_pretrained makes ssl connection event though I provide cache_dir?
