### ISSUE TITLE
Suggestion: exception handling for out-of-vocab in pretrained model

### ISSUE THREAD

**Issue by sdeva14** [huggingface/pytorch-pretrained-BERT#482]
Dear concern,

I appreciate your favor for public implementation.
As you know, all NLP people have an interest in applying your gorgeous model to every NLP problem.

I am writing this to suggest to add exception handling or warning message about out-of-vocabulary when a pretrained model is used.

I had been suffered by an error message for two days with checking every my code, naturally, I had believed it is my programming problem again :)
Then I discovered that it is out-of-vocab problem.
The pretrained BERT model has vocab size 28996, but my dataset with BERT subword tokenizer has more than 30000 vocab.
Then it is an error, when the BERT model meets an index higher than 28996.

If we know the problem, a solution is quite simple, filtering or replacing it to UNK index.
Error messages are caused from somewhat embedding parts in CPU mode, but it was unclear to identify GPU mode, thus other people might be suffered like me.

I know the pretrained model is not designed for application, long documents with unusual vocabulary.
However, I believe many people will appreciate your favor if you add exception handling or warning message.
If you already have recognized the issue, please ignore this message :)

Best
Sungho

**Comment by thomwolf** [comment]
Hi Sungho,
This should already be taken care of by the BertTokenizer which defaults on the `unk` token when a sub-word is not in the vocabulary (see [here](https://github.com/huggingface/pytorch-pretrained-BERT/blob/master/pytorch_pretrained_bert/tokenization.py#L372)).
What BERT model are you using?
Do you have a simple example you can share so I can try to reproduce the behavior?

**Comment by sdeva14** [comment]
Hi Tomas,

The way I see it, it should have been covered, then I might have bypassed proper usage.

1. My code usage is as follows:
    self.tokenizer = BertTokenizer.from_pretrained("bert-base-uncased", do_lower_case=True)
    ...
    tokens_sent = self.tokenizer.tokenize(sent)
    id_sent = self.tokenizer.convert_tokens_to_ids(tokens_sent)
    ...
    self.encoder = BertModel.from_pretrained("bert-base-cased")
    ...

2. Error cases are as follows:
    2.1. Case1 with index value 29144
    original sentence: first, it was the old timers at the reservoir campground.
    id_sent: [2034, 1010, 2009, 2001, 1996, 2214, 25309, 2015, 2012, 1996, 8071, 29144, 1012, 102]

    2.2. Case2 with index value 29323
    original sentence: hes sacting time and sec from add perso doesn’t mic at all because there could hou old –timers and don’t know once thou are tailoring around her, to save, to goo shouldn’t take advice from them because goo could end its line this nidsnes transitin califend doesn’t and how feres how could now do it, to let some or therefore so be dehydrated.
    id_sent: [2002, 2015, 17266, 3436, 2051, 1998, 10819, 2013, 5587, 2566, 6499, 2987, 1521, 1056, 23025, 2012, 2035, 2138, 2045, 2071, 7570, 2226, 2214, 1516, 25309, 2015, 1998, 2123, 1521, 1056, 2113, 2320, 15223, 2024, 22701, 2075, 2105, 2014, 1010, 2000, 3828, 1010, 2000, 27571, 5807, 1521, 1056, 2202, 6040, 2013, 2068, 2138, 27571, 2071, 2203, 2049, 2240, 2023, 9152, 5104, 5267, 6671, 2378, 10250, 29323, 4859, 2987, 1521, 1056, 1998, 2129, 10768, 6072, 2129, 2071, 2085, 2079, 2009, 1010, 2000, 2292, 2070, 2030, 3568, 2061, 2022, 2139, 10536, 7265, 3064, 1012, 102]

3. Version info
    python: Python 3.7.2
    torch: 1.0.0
    pytorch-pretrained-bert: 0.6.1
    CUDA: 8.0.61_375.26
    GCC: 5.4.0-2.26
    GPU device: Pascal P40

Please understand I cannot share the entire code and information yet before submission.
But let me know if you need more information or more error cases in this dataset.


Best
Sungho

**Comment by sdeva14** [comment]
Hi Tomas,

It is really shame to describe, I think it is just my typo problem again :(
Please ignore this issue.

You are absolutely right, there is an exception handling.
Just I loaded a wrong model in the BertModel later after tokenizing.
"bert-base-cased" in the model part, Instead of "bert-base-uncased", which has a smaller vocab size than "uncased".

I am so sorry to waste your time, and appreciate your favor again! :)

Best
Sungho

**Comment by thomwolf** [comment]
Ok make sense, good to know.
So there is no problem in the end?

**Comment by sdeva14** [comment]
Yep, only my embarrassing here :)

Though there is no performance change, but I believe it is not a problem of pretrained model at all, but 
 just different application.

Thus, no problem for implementation at all, I appreciate it!

**Comment by thomwolf** [comment]
Ok, let's close the issue then. Feel free to open a new one if you have other problems.

**Comment by culcomp** [comment]
May I know why cased vocabulary is smaller than uncased?
