### ISSUE TITLE
UnboundLocalError: local variable 'special_tokens_file' referenced before assignment

### ISSUE THREAD

**Issue by yaroslavvb** [huggingface/pytorch-pretrained-BERT#497]
Happens during this
```enc = GPT2Tokenizer.from_pretrained('gpt2')```

```
  File "example_lambada_prediction_difference.py", line 23, in <module>
    enc = GPT2Tokenizer.from_pretrained(model_name)
  File "/bflm/pytorch-pretrained-BERT/pytorch_pretrained_bert/tokenization_gpt2.py", line 134, in from_pretrained
    if special_tokens_file and 'special_tokens' not in kwargs:
UnboundLocalError: local variable 'special_tokens_file' referenced before assignment
```
Looking at offending file, it looks like there's a path for which `special_tokens_file` is never initialized

https://github.com/huggingface/pytorch-pretrained-BERT/blob/3d78e226e68a5c5d0ef612132b601024c3534e38/pytorch_pretrained_bert/tokenization_gpt2.py#L134

**Comment by thomwolf** [comment]
Yes, this should be fixed by #498.
