### ISSUE TITLE
error when do python3 run_squad.py

### ISSUE THREAD

**Issue by directv00** [huggingface/pytorch-pretrained-BERT#499]
Hello,
I am newbie of pytorch-pretrained-Bert.
After successfully converted from init-checkpoint of tensorflow to pytorch bin,
I found an error when I do run_squad.
Guessing I should've included some configuration ahead, could anyone can help?
See below.
```bash
File "run_squad.py", line 37, in <module>
    from pytorch_pretrained_bert.file_utils import PYTORCH_PRETRAINED_BERT_CACHE, WEIGHTS_NAME, CONFIG_NAME
ImportError: No module named pytorch_pretrained_bert.file_utils
```

**Comment by thomwolf** [comment]
Did you install pytorch-pretrained-bert as indicated in the README?
`pip install pytorch_pretrained_bert`

You don't have to convert the checkpoints yourself, there are already converted.

Try reading the installation and usage sections of the README.

**Comment by directv00** [comment]
Of cause I installed,
More precisely, error code is slightly changed.
-------------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "run_squad.py", line 37, in <module>
    from pytorch_pretrained_bert.file_utils import PYTORCH_PRETRAINED_BERT_CACHE, WEIGHTS_NAME, CONFIG_NAME
ImportError: cannot import name WEIGHTS_NAME

**Comment by thomwolf** [comment]
Hmm you are right, the examples are compatible with `master` only now that we have a new token serialization. I guess we'll have to do a new release (0.6.2) today so everybody is on the same page.
Let me do that.

**Comment by thomwolf** [comment]
Actually, we'll wait for the merge of #506.

In the meantime you can install from source and it should work.

**Comment by directv00** [comment]
Could you give me more detailed explanation about install from source?
---------------------------------------------------------------------------------
pip install [--editable] .

**Comment by directv00** [comment]
Oh it's done immediately when I installed from source. Thanks.

**Comment by thomwolf** [comment]
Ok great.

Just a side note on writing messages in github: you should add triple-quotes like this: \``` before and after the command line, errors and code you are pasting. This way it's easier to read.

Ex:
\```
pip install -e .
\```

will display like:
```
pip install -e .
```

**Comment by directv00** [comment]
Good point(triple quotes)
I didn't know what to do, but now I have it all.
Thanks.

**Comment by YanZhangADS** [comment]
> Actually, we'll wait for the merge of #506.
> 
> In the meantime you can install from source and it should work.

how to "install from source"?

**Comment by yumere** [comment]
@YanZhangADS 

You can install from source like below
```
git clone https://github.com/huggingface/pytorch-pretrained-BERT.git
cd pytorch-pretrained-BERT
python setup.py intall
```

**Comment by dumitrescustefan** [comment]
Same problem with "ImportError: cannot import name WEIGHTS_NAME". However, after building **0.6.1** from source, I get: 
```
from pytorch_pretrained_bert.optimization import BertAdam, warmup_linear
    ImportError: cannot import name 'warmup_linear'
```
I don't need the warmup, so I removed the import, but letting you guys know that this is an import error as well. Thanks!

**Comment by thomwolf** [comment]
Thanks for that @dumitrescustefan, we're working on it in #518.
I'm closing this issue for now as we start to deviate from the original discussion.

**Comment by goyalsaransh97** [comment]
I just built from source. I'm still getting the same error as in original issue.

**Comment by al-yakubovich** [comment]
The version 0.4.0 doesn't give this issue.
pip install pytorch_pretrained_bert==0.4.0
