### ISSUE TITLE
How to obtain attention values for each layer 

### ISSUE THREAD

**Issue by serenaklm** [huggingface/pytorch-pretrained-BERT#502]
Hi all, 

Please correct me if I am wrong. 

From my understanding, The encoded values for each layer (12 of them for base model) would be returned when we run our results through the pre-trained model. 
However, I would like to examine the self-attention values for each layer. Is there a way I can extract that out? 

Regards

**Comment by thomwolf** [comment]
Not really.
You should build a new sub-class of `BertPreTrainedModel` which is identical to `BertModel`but send back self-attention values in addition to the hidden states.

**Comment by serenaklm** [comment]
I see. Thank you!

**Comment by serenaklm** [comment]
Hi, 

Just to add on. If this is what I would be doing, would it be advisable to fine-tune the weights for the pretrained model? 

Regards

**Comment by thomwolf** [comment]
Probably.
It depends on what's your final use-case.
