### ISSUE TITLE
Missing options/arguments in run_squad.py for BERT Large

### ISSUE THREAD

**Issue by avisil** [huggingface/pytorch-pretrained-BERT#51]
Thanks for the great code..However, the `run_squad.py` for BERT Large seems to not have the `vocab_file`  and `bert_config_file` (or other) options/arguments. Did you push the latest version?
Also, it is looking for a pytorch model file (a bin file). Does it need to be there?

I also had to add this line to the file to make BERT base to run on Squad 1.1:
`parser.add_argument('--do_lower_case', action="store_true", default=True, help="Lowercase the input")`

**Comment by thomwolf** [comment]
Yes, the readme example was for an older version. I have updated them with the simplified parameters used in the current release. Thanks.
