### ISSUE TITLE
Adam optimiser not following Pytorch conventions

### ISSUE THREAD

**Issue by tonianelope** [huggingface/pytorch-pretrained-BERT#510]
Both [BertAdam](https://github.com/huggingface/pytorch-pretrained-BERT/blob/master/pytorch_pretrained_bert/optimization.py) and [OpenAIAdam](https://github.com/huggingface/pytorch-pretrained-BERT/blob/master/pytorch_pretrained_bert/optimization_openai.py) don't follow the pytroch convetion to define the `betas` parameter for  [Adam Optimisers](https://pytorch.org/docs/stable/optim.html#torch.optim.Adam) as a tuple, but instead has parameters `b1` and `b2`.

Pytorch based libraries like fastai expect the optimizer `betas` to be a tuple.
Any reason `b1/2` is used instead of a tuple? Would be great to change so the optimisers can integrate with other pytorch libraries.

**Comment by thomwolf** [comment]
We could update that indeed, that's just a relic of the Tensorflow conversion.
Do you want to submit a PR? Otherwise I'll do it when I work on the next release.
