### ISSUE TITLE
How many epochs are necessary for finetuning BERT?

### ISSUE THREAD

**Issue by search4mahesh** [huggingface/pytorch-pretrained-BERT#513]
Hi,
Could somebody provide some insights on how many epochs are necessary for finetuning bert model?
Google BERT has 100000 steps.(total_data/batch_size)

flags.DEFINE_integer("num_train_steps", 100000, "Number of training steps.") 

Thanks
Mahesh

**Comment by SivilTaram** [comment]
I have tried to finetune GPT rather than BERT. An appropriate running epochs is **3** in the generation setting, including learning on embedding of some custom special tokens. Hope it help you :)
