### ISSUE TITLE
ADD ERNIE

### ISSUE THREAD

**Issue by nghuyong** [huggingface/pytorch-pretrained-BERT#514]
Can we add a new model ERNIE?
ERNIE is based on the Bert model and has better performance on Chinese NLP tasks.
Github address: https://github.com/PaddlePaddle/LARK/tree/develop/ERNIE
paper:  https://arxiv.org/abs/1904.09223
Thanks

**Comment by thomwolf** [comment]
Hi @nghuyong, I won't convert ERNIE but I'm open to welcome a PR if somebody want to give it a try.

Also, note that unlike examples, a PR with a new model should have a configuration class, tests, a conversion script and be documented like the other models in the library.

**Comment by nghuyong** [comment]
I do implement that converting ERNIE to huggingface's format
The address is https://github.com/nghuyong/ERNIE-Pytorch
Welcome to use and open issue if have problems
