### ISSUE TITLE
No GPT2 model

### ISSUE THREAD

**Issue by lcswillems** [huggingface/pytorch-pretrained-BERT#519]
I tried to load the `gpt2` model listed in the README.md, but I got this error:

```
Model name 'gpt2' was not found in model name list (bert-base-uncased, bert-large-uncased, bert-base-cased, bert-large-cased, bert-base-multilingual-uncased, bert-base-multilingual-cased, bert-base-chinese). We assumed 'gpt2' was a path or url but couldn't find any file associated to this path or url.
```

The code I used:
```
# Load pre-trained model tokenizer (vocabulary)
tokenizer = BertTokenizer.from_pretrained('gpt2')

# Load pre-trained model (weights)
model = BertModel.from_pretrained('gpt2')
_ = model.eval()
```

**Comment by thomwolf** [comment]
Do you have a working internet connection?
We should probably improve the error messages here, 2 different error are bundled in this error.

**Comment by lcswillems** [comment]
Yes, I have an internet connection. I am able to download the other networks.

**Comment by thomwolf** [comment]
Oh wait, you are mixing two models here.
GPT-2 and BERT are two different architectures.
If you want to use GPT-2 do:
```
tokenizer = GPT2Tokenizer.from_pretrained('gpt2')
model = GPT2Model.from_pretrained('gpt2')
```
An example of usage is [here in the readme](https://github.com/huggingface/pytorch-pretrained-BERT#openai-gpt-2)

**Comment by lcswillems** [comment]
Okay, thank you! Sorry, for this. :)
