### ISSUE TITLE
Will BERT weights for SQuAD be released?

### ISSUE THREAD

**Issue by lcswillems** [huggingface/pytorch-pretrained-BERT#526]
Hi,

Are you going to release the weights after training on SQuAD 2.0?
Thank you for your great work.

Best,
Lucas Willems

**Comment by thomwolf** [comment]
Hi Lucas, probably not.

The goal of this repository is to provide easy access to pretrained model for transfer learning research. 

Providing downstream task models will make us handle a combinatory explosion of combinations to provide the various pretrained BERT models fine-tuned on each GLUE/SQuAD task with hyper-parameters optimization and all the relevant adaptation decision that are still mostly open research questions.

But we do provide examples for fine-tuning that gives decent results and can be trained in a reasonable time on standard cloud compute.

**Comment by Santosh-Gupta** [comment]
@lcswillems were you able to find the weights anywhere else?

**Comment by Santosh-Gupta** [comment]
Looks like HF released them after all

https://huggingface.co/transformers/pretrained_models.html
