### ISSUE TITLE
__init__() got an unexpected keyword argument 'do_basic_tokenize'

### ISSUE THREAD

**Issue by lcswillems** [huggingface/pytorch-pretrained-BERT#528]
In the README, this line is written:

```
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased', do_lower_case=True, do_basic_tokenize=True)
```

But when I execute it, I get this error:

```
__init__() got an unexpected keyword argument 'do_basic_tokenize'
```

**Comment by thomwolf** [comment]
Which version of pytorch-pretrained-bert are you using?
Can you give the full error message to see which call to `__init__()` is failing?
We should have the keyword argument [here](https://github.com/huggingface/pytorch-pretrained-BERT/blob/3d78e226e68a5c5d0ef612132b601024c3534e38/pytorch_pretrained_bert/tokenization.py#L77)

**Comment by lcswillems** [comment]
I have the last version (0.6.1).

This is what I have on my computer:

![image](https://user-images.githubusercontent.com/5437552/56668476-db88db00-66af-11e9-92a1-5704ae4c157e.png)
