### ISSUE TITLE
key error in BertQuestionAsnwering predict?

### ISSUE THREAD

**Issue by search4mahesh** [huggingface/pytorch-pretrained-BERT#538]
Hi,

I am getting key error while using BertQuestionAsnwering predict?
I am breaking following loop after 10 iterations
for input_ids, input_mask, segment_ids, example_indices in tqdm(eval_dataloader, desc="Evaluating", disable=local_rank not in [-1, 0]):

Thanks
Mahesh

Error:

KeyError                                  Traceback (most recent call last)
<ipython-input-87-6ac2c26449fb> in <module>()
     41                   do_lower_case, output_prediction_file,
     42                   output_nbest_file, output_null_log_odds_file, verbose_logging,
---> 43                   version_2_with_negative, null_score_diff_threshold)

/content/run_squad.py in write_predictions(all_examples, all_features, all_results, n_best_size, max_answer_length, do_lower_case, output_prediction_file, output_nbest_file, output_null_log_odds_file, verbose_logging, version_2_with_negative, null_score_diff_threshold)
    473         null_end_logit = 0  # the end logit at the slice with min null score
    474         for (feature_index, feature) in enumerate(features):
--> 475             result = unique_id_to_result[feature.unique_id]
    476             start_indexes = _get_best_indexes(result.start_logits, n_best_size)
    477             end_indexes = _get_best_indexes(result.end_logits, n_best_size)

KeyError: 1000000088

**Comment by thomwolf** [comment]
You found a solution?

**Comment by search4mahesh** [comment]
@thomwolf , I made mistake in code, Repo code works just fine. Hence closed issue.
Thanks for this amazing repo :thumbsup:

**Comment by amos814** [comment]
How to solve this problem?

**Comment by shubhangi-tandon** [comment]
what was the solution ? Im seeing the same problem

**Comment by LysandreJik** [comment]
Do you mind opening a new issue with your problem?

**Comment by julianvenhuizen** [comment]
Hi, I'm having the same error as described above. Is anyone able to post their solution?
