### ISSUE TITLE
Can we use 'bert-base-uncased' to question_answer just for start, rather rather than run_squad pretraining?

### ISSUE THREAD

**Issue by search4mahesh** [huggingface/pytorch-pretrained-BERT#539]
Hi, 
Can we use 'bert-base-uncased' to question_answer just for start, rather rather than run_squad pretraining?

model = BertForQuestionAnswering.from_pretrained('bert-base-uncased') 

Thanks
Mahesh

**Comment by thomwolf** [comment]
Hi, no you need to fine tune the model on a question answering task like SQuAD before you can use it
