### ISSUE TITLE
example in BertForSequenceClassification() conflicts with the api 

### ISSUE THREAD

**Issue by labixiaoK** [huggingface/pytorch-pretrained-BERT#54]
Hi, firstly, admire u for the great job.  but I encounter 2 problems when i use it:
**1**. `UnicodeDecodeError: 'gbk' codec can't decode byte 0x85 in position 4527: illegal multibyte sequence`,
same problem as ISSUE 52 when I excute the `BertTokenizer.from_pretrained('bert-base-uncased')`, but I successfully excute `BertForNextSentencePrediction.from_pretrained('bert-base-uncased')`, >.<
**2**. in the pytorch-pretrained-BERT/pytorch_pretrained_bert/modeling.py, 
line 761 -->     ```
   `token_type_ids`: an optional torch.LongTensor of shape [batch_size, sequence_length] **with the token
            types indices selected in [0, 1]**. Type 0 corresponds to a `sentence A` and type 1 corresponds to
            a `sentence B` token (see BERT paper for more details).
```
but in the following example,  in **line 784**-->     `token_type_ids = torch.LongTensor([[0, 0, 1], [0, **2**, 0]])`, why the '2' appears?  I am confused.  Otherwise, is the situation similar to '0, 1, 0 ' correct ? Or it should be similar to [000000111111] , that is continuous '0' and continuous '1' ?
ty.

**Comment by thomwolf** [comment]
Hi,
(1) is solved on master. I will release a new release soon with the fixes on pip. In the mean time you can install from sources if you want.
I fixed the typo in the docstring you mention in (2), thanks, it should be a `1` instead of a `2`.
