### ISSUE TITLE
no to_json_file(file) in BERT

### ISSUE THREAD

**Issue by seanie12** [huggingface/pytorch-pretrained-BERT#540]
Hi, https://github.com/huggingface/pytorch-pretrained-BERT/blob/master/examples/run_squad.py#L1035
in the line 1035, I cannot use config.to_json_file(output_config_file) because there is no such function.
Instead I use
`file = model_to_save.config.to_json_string()`
`with open(file_path, "w") as f:`
`    f.write(file)`
Is it correct way to save config file?

**Comment by thomwolf** [comment]
Are you using the latest release (0.6.2) ?

**Comment by seanie12** [comment]
Yes I am.

**Comment by thomwolf** [comment]
Strange, `to_json_file` should be provided in 0.6.2 (cf code [here](https://github.com/huggingface/pytorch-pretrained-BERT/blob/e6cf62d49945e6277b5e4dc855f9186b3f789e35/pytorch_pretrained_bert/modeling.py#L222) and the associated test [here](https://github.com/huggingface/pytorch-pretrained-BERT/blob/68a889ee43916380f26a3c995e1638af41d75066/tests/modeling_test.py#L258))

**Comment by seanie12** [comment]
Thanks :0) I'll check the version and code again.

**Comment by seanie12** [comment]
After removing the package and install, the problem solved
