### ISSUE TITLE
Any way to reduce the model size to <250mb?

### ISSUE THREAD

**Issue by bolaft** [huggingface/pytorch-pretrained-BERT#541]
Google Cloud's online prediction service has a 250mb limit for uploaded models. I don't think I have ever seen a BERT model that small. Casting all tensors to half precision reduces the model to ~350mb, is there any way to go even further than that?

**Comment by Rocketknight1** [comment]
Probably not - it would certainly be possible to make a smaller BERT model that would fit into this size, but all of the available pre-trained models have too many parameters, so you'd have to train it from scratch (which is very slow, and isn't something this repo supports yet).
