### ISSUE TITLE
Training Transformer XL from scratch

### ISSUE THREAD

**Issue by anshuman1992** [huggingface/pytorch-pretrained-BERT#561]
Hello,

I'm trying to train a transformer XL model from scratch by combining the architecture code from this library and training code from the official paper repo. But this yields to NaNs during training, just wanted to clarify the recommended way to initialize a new model.

Im doing it by,
```
architecture = TransfoXLConfig().from_json_file(args.config_path)
 model = TransfoXLLMHeadModel(architecture)
```
Is there a bug in this?

**Comment by thomwolf** [comment]
This looks good to me

**Comment by ksopyla** [comment]
@anshuman1992 could you share a code snippet/gist used for training TransformerXL model?

**Comment by joistick11** [comment]
@anshuman1992 this will be great for me too
