### ISSUE TITLE
about pytorch 1.1.0 rerlease

### ISSUE THREAD

**Issue by yeontaek** [huggingface/pytorch-pretrained-BERT#567]
Hi today pytorch 1.1.0 release(https://github.com/pytorch/pytorch/releases/tag/v1.1.0)

In version 1.1.0, added a new module implementing Multi-headed-Attention.

And various bugs have been modified.

Do you plan to update to suit that version?

**Comment by thomwolf** [comment]
Hi,

The repo is compatible with PyTorch 1.1.0.

But, we probably won't switch to PyTorch Multi-headed-Attention module since this would mean refactoring all the models and adding complexity to the tensorflow conversion codes for unclear gains.
