### ISSUE TITLE
Missing function convert_to_unicode in tokenization.py

### ISSUE THREAD

**Issue by ptrichel** [huggingface/pytorch-pretrained-BERT#57]
The function _convert_to_unicode_ is not in tokenization.py but used to be there in v0.1.2. When fine tuning with run_classifier.py, you get an ImportError: cannot import name 'convert_to_unicode'.

https://github.com/huggingface/pytorch-pretrained-BERT/blob/ce37b8e4819142171b61558e64f7dcb0286e9937/examples/run_classifier.py#L33

**Comment by thomwolf** [comment]
Fixed in master, thanks!
