### ISSUE TITLE
Resetting current_random_doc and current_doc

### ISSUE THREAD

**Issue by crowegian** [huggingface/pytorch-pretrained-BERT#579]
In the class BERTDataset the two variables `self.current_random_doc` and `self.current_doc` are never reset to 0, even when the corpus is closed and reopened. Is it supposed to work this way? I'd think it would run into issues on a small corpus where one counter gets to the same document but the counter is different because it was opened a second time.

https://github.com/huggingface/pytorch-pretrained-BERT/blob/3ae8c8be1e3fc770968cd3fdb3b643e0b166e540/examples/lm_finetuning/simple_lm_finetuning.py#L42-L231

**Comment by thomwolf** [comment]
Hmm maybe @Rocketknight1 have an insight on this?
