### ISSUE TITLE
BERT + PyTorch + XLA

### ISSUE THREAD

**Issue by snakers4** [huggingface/pytorch-pretrained-BERT#583]
Hi,

Many thanks for your amazing library!
Even though no models were shared for Russian, we used your interfaces with success when doing some [research](https://towardsdatascience.com/complexity-generalization-computational-cost-in-nlp-modeling-of-morphologically-rich-languages-7fa2c0b45909).

Anyway here is my question.
Did you try [this](https://github.com/pytorch/xla/tree/master)?
At least on the surface it looks like they boast PyTorch + TPU.
Would also be cool to know if anyone had experience in running anything with XLA.

Many thanks!

**Comment by wuyinzhenjun** [comment]
Do u mean this one? [link](https://news.developer.nvidia.com/nvidia-achieves-4x-speedup-on-bert-neural-network/)

**Comment by snakers4** [comment]
No, I mean this repo
https://github.com/pytorch/xla/tree/master

Looks like Facebook and Google want to make pytorch on TPU


On May 6, 2019 9:14:25 AM GMT+03:00, chunbo dai <notifications@github.com> wrote:
>Do u mean this one?
>[link](https://news.developer.nvidia.com/nvidia-achieves-4x-speedup-on-bert-neural-network/)
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/huggingface/pytorch-pretrained-BERT/issues/583#issuecomment-489510379

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
