### ISSUE TITLE
[Question] Cross-lingual sentence representations

### ISSUE THREAD

**Issue by shoegazerstella** [huggingface/pytorch-pretrained-BERT#596]
Hi, 
Would it be possible to integrate also a BERT model for cross-lingual sentence representations? 
Something like, for example, the `XNLI-15` model in [https://github.com/facebookresearch/XLM](https://github.com/facebookresearch/XLM).
Thanks!

**Comment by thomwolf** [comment]
Hi @shoegazerstella well XLM is already pretty much as powerful as BERT and focused on cross-lingual sentence representations so I would go directly for it instead of BERT.

**Comment by shoegazerstella** [comment]
Thanks @thomwolf, 
Are you considering integrating something for cross-lingual representations in the `pytorch-pretrained-BERT` library in the near future?

**Comment by thomwolf** [comment]
Not in the short-term
