### ISSUE TITLE
GPT-2 Tokenizer error!

### ISSUE THREAD

**Issue by PhungVanDuy** [huggingface/pytorch-pretrained-BERT#638]
I tried to use GPT-2 to encode with `text = "This story gets more ridiculous by the hour! And, I love that people are sending these guys dildos in the mail now. But… if they really think there's a happy ending in this for any of them, I think they're even more deluded than all of the jokes about them assume."` but it error. 

![Screenshot from 2019-05-24 14-31-30](https://user-images.githubusercontent.com/28798474/58310361-a8fa0b80-7e30-11e9-9554-8d34c2b9f968.png)

**Comment by iptmt** [comment]
Maybe you can find the solution at #537

**Comment by PhungVanDuy** [comment]
> Maybe you can find the solution at #537

Thank for your support! It works for me!
