### ISSUE TITLE
GPT-2 medium and large release?

### ISSUE THREAD

**Issue by g-karthik** [huggingface/pytorch-pretrained-BERT#665]
I presume the below model is GPT-2 small.

https://github.com/huggingface/pytorch-pretrained-BERT/blob/ee0308f79ded65dac82c53dfb03e9ff7f06aeee4/pytorch_pretrained_bert/modeling_gpt2.py#L42

When do you plan on supporting the medium (already released by OpenAI) and large versions (not released by OpenAI) of GPT-2?

Thanks!

**Comment by julien-c** [comment]
Take a look at the `attention` branch @g-karthik:

https://github.com/huggingface/pytorch-pretrained-BERT/blob/attention/pytorch_pretrained_bert/modeling_gpt2.py#L42-L45

**Comment by g-karthik** [comment]
Thanks @julien-c, I did not look at the file in the `attention` branch!

**Comment by g-karthik** [comment]
What is the recommended hardware setup for fine-tuning GPT2 medium?
