### ISSUE TITLE
Transformer XL ProjectedAdaptiveLogSoftmax bug (maybe?)

### ISSUE THREAD

**Issue by shashwath94** [huggingface/pytorch-pretrained-BERT#678]
In <a href="https://github.com/huggingface/pytorch-pretrained-BERT/blob/master/pytorch_pretrained_bert/modeling_transfo_xl_utilities.py#L120">this line</a>, shouldn't the output be assigned to `out` when `n_clusters` is 0? Otherwise we run into `UnboundLocalError: local variable 'out' referenced before assignment`

**Comment by thomwolf** [comment]
Yes! We don't see that when we use the pre-trained model because the number of clusters is greater than zero anyway. Will fix.

**Comment by shashwath94** [comment]
Thank you. I created a PR since it was a small bug. #690
