### ISSUE TITLE
"Received 'killed' signal" during the circleci python3 build after submitting PR

### ISSUE THREAD

**Issue by chrisyue1998** [huggingface/pytorch-pretrained-BERT#703]
I submitted a PR after modifying convert_gpt2_checkpoint_to_pytorch.py, and my build_py2 test passed, but I received a very vague error from build_py3 (as written in the title of this issue) that caused my build to fail. Does anyone have any ideas as to where the issue could be?

Edit: Attached image below
<img width="625" alt="Screen Shot 2019-06-19 at 3 48 25 PM" src="https://user-images.githubusercontent.com/39981081/59795692-c8f2e280-92a9-11e9-8aa1-77cb96c2db33.png">

**Comment by thomwolf** [comment]
Yeah I've removed the memory-heavy tests

**Comment by chrisyue1998** [comment]
Thanks!
