### ISSUE TITLE
layer_norm_eps

### ISSUE THREAD

**Issue by suchithtuple** [huggingface/pytorch-pretrained-BERT#709]
In [modeling.py](https://github.com/huggingface/pytorch-pretrained-BERT/blob/c304593d8fa93f25febe1458c63497a846749c89/pytorch_pretrained_bert/modeling.py#L303) why `self.layer_norm_eps` is written even config don't have these parameter. Check [here](https://github.com/google-research/bert#pre-trained-models)

Or I am missing something.

**Comment by thomwolf** [comment]
Because some people wanted to configure this: https://github.com/huggingface/pytorch-pretrained-BERT/pull/585

**Comment by suchithtuple** [comment]
So I have to add `config.layer_norm_eps = 1e-12` if I am taking the config from the link above ?

**Comment by thomwolf** [comment]
You don't need to, it's the default value when instantiating a `BertConfig` class.

**Comment by suchithtuple** [comment]
When I printed `dir(bert_config)` I am not able to see layer_norm_eps.

**Comment by suchithtuple** [comment]
I have figure out the problem. I have to initialize like this `BertConfig.from_json_file(config_file_path)` but rather I have done like this `BertConfig(config_file_path)`. My bad :disappointed: 

Thank you for the image. Closing the issue.
