### ISSUE TITLE
Embedding and predictions in one forward pass

### ISSUE THREAD

**Issue by lcswillems** [huggingface/pytorch-pretrained-BERT#719]
Is it possible to mix `BertModel` and `BertForMaskedLM`? i.e. is it possible to get the embedding and the predictions in one forward pass?

**Comment by thomwolf** [comment]
Yes, just make your own PyTorch model taking inspiration from BertModel and BertForMaskedLM

**Comment by lcswillems** [comment]
Okay, thank you :)
