### ISSUE TITLE
Cannot reproduce results from version 0.4.0

### ISSUE THREAD

**Issue by hguan6** [huggingface/pytorch-pretrained-BERT#743]
Hi, I have a research project that I did a few months ago. Now I have problem reproducing results of 0.4.0, and unfortunately, I lost version 0.4.0. Can you please send me the code of this version to hguan6@asu.edu? In fact, I am not quite sure it's 0.4.0, but I remember I did it in March 2019.

**Comment by thomwolf** [comment]
`pip install pytorch-pretrained-bert==0.4.0` should work normally

**Comment by thomwolf** [comment]
Though if you did it with the latest release in March 2019 it was probably more 0.6.1 (see the list and dates here: https://github.com/huggingface/pytorch-pretrained-BERT/releases) so `pip install pytorch-pretrained-bert==0.6.1`

**Comment by hguan6** [comment]
Thank you!

**Comment by hguan6** [comment]
It works. Thank you!
