### ISSUE TITLE
GPT-2 language model decoding method

### ISSUE THREAD

**Issue by cdjhz** [huggingface/pytorch-pretrained-BERT#768]
I am wondering what is the official decoding method when evaluating the language model? The  doc says `run_gpt2.py` implement the beam-search. While to me, it seems it's still greedy search with sampling.

**Comment by thomwolf** [comment]
`run_gpt2` has top-K which is better than beam-search for high-entropy tasks like open-domain generation. The coming release example (currently on the xlnet branch to be merged with master on Monday) will have top-K and Nucleus sampling (see Holtzman et al. http://arxiv.org/abs/1904.09751)

**Comment by ehsan-soe** [comment]
Hi,
Is it possible to include beam search decoding in ```run_generation.py``` ?

**Comment by balabanahei** [comment]
hope that beam search appears in run_generation.py

**Comment by thomwolf** [comment]
We'll add it

**Comment by Diego999** [comment]
@thomwolf I see that run_generation.py has disappeared and beam_search does not exist anymore, nor in transformers/generate. Where could we find the implementation of batch beam_search in this repo ?

**Comment by rlouf** [comment]
You can’t... so far. We are reworking the API for greedy decoding and sampling, and will work on beam search afterwards.
