### ISSUE TITLE
Performance dramatically drops down without training. 

### ISSUE THREAD

**Issue by DariaD** [huggingface/pytorch-pretrained-BERT#771]
I use run_classivier and run_squad as it is shown in README. 
If I remove `--do_train` (I already tuned the model and just want to evaluate one more time or with different development set) I expect that result would be the same but performance drops down. 

For example, SQuAD:
with training:  `{"exact_match": 81.35288552507096, "f1": 88.49520505241821}`
without training: `{"exact_match": 0.21759697256385999, "f1": 7.391520686954715}`

I tried my own processor with binary classification (not up to date code though) and without training the value` 1 `only was predicted.

Thank you in advance for any comments.

**Comment by thomwolf** [comment]
If you want to evaluate only, you have to set `--output_dir` to the path of your previously trained model. Otherwise, the script will use the original model.
