### ISSUE TITLE
Cannot load 'bert-base-german-cased'

### ISSUE THREAD

**Issue by laifi** [huggingface/pytorch-pretrained-BERT#772]
`tokenizer = BertTokenizer.from_pretrained('bert-base-german-cased')`

**Output:**

> Model name 'bert-base-german-cased' was not found in model name list (bert-base-uncased, bert-large-uncased, bert-base-cased, bert-large-cased, bert-base-multilingual-uncased, bert-base-multilingual-cased, bert-base-chinese). We assumed 'bert-base-german-cased' was a path or url but couldn't find any file associated to this path or url.

**Comment by laifi** [comment]
Also downloading the model and load it directly doesn't work for me :

```
!wget https://int-deepset-models-bert.s3.eu-central-1.amazonaws.com/pytorch/bert-base-german-cased.tar.gz
!tar -xvzf bert-base-german-cased.tar.gz
tokenizer = BertTokenizer.from_pretrained('pytorch_model.bin') 
```
**Error :** 

> UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

**Comment by tholor** [comment]
Hi @laifi, 

I cannot reproduce this issue. Are you sure that you run with the latest code from master branch? It looks suspicious to me that `tokenizer = BertTokenizer.from_pretrained('bert-base-german-cased')` doesn't find the model. 
Can you please check if you have [the according line](https://github.com/huggingface/pytorch-pretrained-BERT/blob/78462aad6113d50063d8251e27dbaadb7f44fbf0/pytorch_pretrained_bert/tokenization.py#L37) in your PRETRAINED_VOCAB_ARCHIVE_MAP? 

For your second approach with downloaded files: 
- be aware that model packaging changed lately from archives to individual files for vocab, model and config (see [here](https://github.com/huggingface/pytorch-pretrained-BERT/pull/688#issuecomment-502991015)). If you really want to download manually you should download the [.bin](https://int-deepset-models-bert.s3.eu-central-1.amazonaws.com/pytorch/bert-base-german-cased-pytorch_model.bin), [bert_config.json](https://int-deepset-models-bert.s3.eu-central-1.amazonaws.com/pytorch/bert-base-german-cased-config.json) and the [vocab file](https://int-deepset-models-bert.s3.eu-central-1.amazonaws.com/pytorch/bert-base-german-cased-vocab.txt) to a folder called "bert-base-german-cased"
- `from_pretrained` expects a model name or path not a .bin . You should try:  BertTokenizer.from_pretrained('YOUR_PATH_TO/bert-base-german-cased') 

Hope that helps!

**Comment by laifi** [comment]
Thank you @tholor  , i installed the package with pip and i cannot find 'bert-german-cased' in PRETRAINED_VOCAB_ARCHIVE_MAP
Now , i tried to reinstall the package from source and it's working .

**Comment by shaked571** [comment]
@laifi  I am keep getting the same error as the one that you got:

> UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

I also tried to reinstall it, how did you fix it?

**Comment by laifi** [comment]
> @laifi I am keep getting the same error as the one that you got:
> 
> > UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
> 
> I also tried to reinstall it, how did you fix it?
 Just i uninstalled the pip package  and  installed it from source (try to don't keep any cache for the package).
Also , the issue is fixed in the last migration from pytorch-pretrained-bert to pytorch-transformers .

**Comment by zahrakolagar** [comment]
Hi,
I also run into the same issue when I try this piece of code in google colab. 
tokenizer = BertTokenizer.from_pretrained('bert-base-german-cased')

**Comment by zahrakolagar** [comment]
> Hi,
> I also run into the same issue when I try this piece of code in google colab.
> tokenizer = BertTokenizer.from_pretrained('bert-base-german-cased')

Ok, the issue is fixed by downloading manually.

**Comment by thaitrinh** [comment]
Hi,
I also have the same issue
