### ISSUE TITLE
Should close the SummaryWriter after using it

### ISSUE THREAD

**Issue by t-yaxli** [huggingface/pytorch-pretrained-BERT#779]
Really appreciate the good work to implement this package! 

I have tried to run the script: [run_glue.py](https://github.com/huggingface/pytorch-pretrained-BERT/blob/xlnet/examples/run_glue.py). When I test with this script, I found some of the scalars add into the SummaryWriter did not appears in TensorBoard. I think the cause of it is that the code leaves the SummaryWriter unclosed.

**Comment by thomwolf** [comment]
Oh yes you are right, thanks it's fixed in the coming release.
