### ISSUE TITLE
how to get the word vector from bert pretrain model ?

### ISSUE THREAD

**Issue by zhangyu68** [huggingface/pytorch-pretrained-BERT#783]
Could you please help me?
I just want to get bert's word vector,but I only can get the encoder's result. How can I get the word vector before data inputing the encoder model ?
Thank you !

**Comment by thomwolf** [comment]
This will be possible in the new release out soon.

**Comment by zhangyu68** [comment]
I find a method that can get the words embeddings.Thank you all the same!
self.model = BertModel.from_pretrained(config.bert_path)
self.word_emb = self.model.embeddings
