### ISSUE TITLE
[bug] from_pretrained  error with from_tf

### ISSUE THREAD

**Issue by shibing624** [huggingface/pytorch-pretrained-BERT#784]
https://github.com/huggingface/pytorch-pretrained-BERT/blob/master/pytorch_pretrained_bert/modeling.py#L721 , the weights_path should be archive_file, and set from_tf to str is better to load finetuned model, like model name is model.ckpt-25000.meta.

**Comment by thomwolf** [comment]
Yeah this is solved in the coming release
