### ISSUE TITLE
numpy.core._internal.AxisError: axis 1 is out of bounds for array of dimension 1

### ISSUE THREAD

**Issue by A-Rain** [huggingface/pytorch-pretrained-BERT#79]
hello, when I am running run_classifier.py with MRPC dataset, there seems to be an mistake. the mistake is as following:
<img width="752" alt="default" src="https://user-images.githubusercontent.com/29532760/49360256-9de0e100-f713-11e8-9a5c-d9f2bc5331e6.PNG">
the mistake is happening when training is over and the model is for evaluating

```
with torch.no_grad():
                tmp_eval_loss, logits = model(input_ids, segment_ids, input_mask, label_ids)
```
here I found the size of logits is []

I'm using python3.5 and torch=0.4.1, I don't know how to fix it.

**Comment by thomwolf** [comment]
Hi, just update the repo to the current master, this should have been fixed this weekend (re-open the issue of it's not).
