### ISSUE TITLE
How to use pre-trained SQUAD model? 

### ISSUE THREAD

**Issue by danyaljj** [huggingface/pytorch-pretrained-BERT#85]
After training squad, I have a model file in a local folder: 

```
-rw-rw-r--  1 khashab2 cs_danr 4.7M Nov 21 19:20 dev-v1.1.json
-rw-rw-r--  1 khashab2 cs_danr 3.4K Nov 29 22:52 evaluate-v1.1.py
drwxrwsr-x  2 khashab2 cs_danr   10 Nov 30 14:57 out2
-rw-rw-r--  1 khashab2 cs_danr  29M Nov 21 19:20 train-v1.1.json
-rw-rw-r--  1 khashab2 cs_danr 490M Nov 29 23:14 train-v1.1.json_bert-base-uncased_384_128_64
-rw-rw-r--  1 khashab2 cs_danr 490M Nov 30 15:05 train-v1.1.json_bert-large-uncased_384_128_64
```

I want to use this pre-trained model to make predictions. Is there any example that I can follow this? (if not any pointers?) I looked into the instructions and didn't find anything relevant on this.

**Comment by thomwolf** [comment]
Hi there are now examples on how you can save and reload the models in the examples (`run_classifier`, `run_squad` and `run_swag`)
